import BanLat.LocallySolid.Completion
import BanLat.LocallySolid.Lebesgue
import BanLat.LocallySolid.LocallyConvexSolid
import BanLat.LocallySolid.WithSeminorms
import BanLat.Examples.CofK.Basic
import Mathlib.Analysis.Real.Cardinality
import Mathlib.Topology.Compactification.OnePoint.Basic
import Mathlib.Topology.UniformSpace.Dini

namespace Aliprantis.Question1

/-- The one-point compactification `A∞` of the set `A` equipped with the discrete topology. -/
abbrev AInfty (A : Type*) := OnePoint (WithDiscreteTopology A)

/-- The vector lattice `C(A∞)` of real-valued continuous functions on `A∞`. -/
abbrev ContinuousFunctions (A : Type*) := C(AInfty A, ℝ)

/-- A point of `A`, viewed as a finite point of its one-point compactification. -/
def finitePoint {A : Type*} (a : A) : AInfty A :=
  (WithTopology.toTopology ⊥ a : WithDiscreteTopology A)

/-- Evaluation of a continuous function at a point of `A∞`, as a linear map. -/
def evaluationLinearMap {A : Type*} (x : AInfty A) :
    ContinuousFunctions A →ₗ[ℝ] ℝ where
  toFun f := f x
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- The lattice seminorm `f ↦ |f(x)|` given by evaluation at `x ∈ A∞`. -/
noncomputable def evaluationLatticeSeminorm {A : Type*} (x : AInfty A) :
    LatticeSeminorm (ContinuousFunctions A) where
  toSeminorm := (normSeminorm ℝ ℝ).comp (evaluationLinearMap x)
  monotone_abs' := by
    intro f g hfg
    simpa [Seminorm.comp_apply, evaluationLinearMap, Real.norm_eq_abs,
      ContinuousMap.abs_apply] using ContinuousMap.le_def.mp hfg x

@[simp]
theorem evaluationLatticeSeminorm_apply {A : Type*} (x : AInfty A)
    (f : ContinuousFunctions A) : (evaluationLatticeSeminorm x).toSeminorm f = |f x| := by
  simp [evaluationLatticeSeminorm, Seminorm.comp_apply, evaluationLinearMap,
    Real.norm_eq_abs]

private lemma evaluationSeminorms_bddAbove {A : Type*} (b : ℕ → A) :
    BddAbove (Set.range fun n =>
      (evaluationLatticeSeminorm (finitePoint (b n))).toSeminorm) := by
  refine ⟨normSeminorm ℝ (ContinuousFunctions A), ?_⟩
  rintro p ⟨n, rfl⟩ f
  simpa [evaluationLatticeSeminorm, Seminorm.comp_apply, evaluationLinearMap] using
    ContinuousMap.norm_coe_le_norm f (finitePoint (b n))

/-- The lattice seminorm `q(f) = sup j, |f(b j)|` from the paper. -/
noncomputable def uniformOnSequenceLatticeSeminorm {A : Type*} (b : ℕ → A) :
    LatticeSeminorm (ContinuousFunctions A) where
  toSeminorm := ⨆ n, (evaluationLatticeSeminorm (finitePoint (b n))).toSeminorm
  monotone_abs' := by
    intro f g hfg
    rw [Seminorm.iSup_apply (evaluationSeminorms_bddAbove b),
      Seminorm.iSup_apply (evaluationSeminorms_bddAbove b)]
    refine ciSup_mono ⟨‖g‖, Set.forall_mem_range.mpr fun n => ?_⟩ ?_
    · simpa [evaluationLatticeSeminorm, Seminorm.comp_apply, evaluationLinearMap] using
        ContinuousMap.norm_coe_le_norm g (finitePoint (b n))
    · intro n
      exact (evaluationLatticeSeminorm (finitePoint (b n))).monotone_abs' hfg

theorem uniformOnSequenceLatticeSeminorm_apply {A : Type*} (b : ℕ → A)
    (f : ContinuousFunctions A) :
    (uniformOnSequenceLatticeSeminorm b).toSeminorm f =
      ⨆ n, |f (finitePoint (b n))| := by
  change (⨆ n, (evaluationLatticeSeminorm (finitePoint (b n))).toSeminorm) f = _
  rw [Seminorm.iSup_apply (evaluationSeminorms_bddAbove b)]
  simp only [evaluationLatticeSeminorm_apply]

/-- The points of `A` outside the distinguished countable subset `range b`. -/
abbrev OutsideSequence {A : Type*} (b : ℕ → A) := {a : A // a ∉ Set.range b}

/-- An index for `q`, represented by `none`, or for one of the `qₐ`, represented by `some a`. -/
abbrev SeminormIndex {A : Type*} (b : ℕ → A) := Option (OutsideSequence b)

/-- The family consisting of `q` and all point-evaluation seminorms `qₐ` off `range b`. -/
noncomputable def latticeSeminormFamily {A : Type*} (b : ℕ → A) :
    SeminormIndex b → LatticeSeminorm (ContinuousFunctions A)
  | none => uniformOnSequenceLatticeSeminorm b
  | some a => evaluationLatticeSeminorm (finitePoint a.1)

/-- The topology `τ` generated by `q` and the point-evaluation seminorms `qₐ`, for
`a ∈ A \ range b`. -/
@[implicit_reducible]
noncomputable def locallyConvexSolidTopology {A : Type*} (b : ℕ → A) :
    TopologicalSpace (ContinuousFunctions A) :=
  (LatticeSeminorm.toSeminormFamily (latticeSeminormFamily b)).moduleFilterBasis.topology'

/-- By construction, `τ` is induced by the lattice seminorm family from the paper. -/
theorem withLatticeSeminorms {A : Type*} (b : ℕ → A) :
    @WithLatticeSeminorms (ContinuousFunctions A) _ _ _ _
      (locallyConvexSolidTopology b) (SeminormIndex b) (latticeSeminormFamily b) := by
  unfold WithLatticeSeminorms
  exact @WithSeminorms.mk ℝ (ContinuousFunctions A) (SeminormIndex b) _ _ _
    (LatticeSeminorm.toSeminormFamily (latticeSeminormFamily b))
    (locallyConvexSolidTopology b) rfl

/-- Equipped with `τ`, `C(A∞)` is a locally convex-solid vector lattice. -/
theorem isLocallyConvexSolidVectorLattice {A : Type*} (b : ℕ → A) :
    @IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) _ _ _ _
      (locallyConvexSolidTopology b) := by
  exact (@isLocallyConvexSolidVectorLattice_iff_exists_withLatticeSeminorms
    (ContinuousFunctions A) _ _ _ _ (locallyConvexSolidTopology b)).2
      ⟨SeminormIndex b, latticeSeminormFamily b, withLatticeSeminorms b⟩

private lemma exists_finitePoint_ne_zero {A : Type*} [Uncountable A]
    {f : ContinuousFunctions A} (hf : f ≠ 0) : ∃ a, f (finitePoint a) ≠ 0 := by
  by_contra h
  simp only [not_exists, not_not] at h
  have htend : Filter.Tendsto
      (fun x : WithDiscreteTopology A => f (x : AInfty A)) Filter.cofinite
      (nhds (f (OnePoint.infty : AInfty A))) :=
    (OnePoint.continuous_iff_from_discrete _).mp f.continuous
  have hzero : (fun x : WithDiscreteTopology A => f (x : AInfty A)) = fun _ => 0 := by
    funext x
    simpa [finitePoint] using h (WithTopology.ofTopology x)
  have hinfty : f (OnePoint.infty : AInfty A) = 0 := by
    apply tendsto_nhds_unique htend
    rw [hzero]
    exact tendsto_const_nhds
  apply hf
  ext x
  induction x using OnePoint.rec with
  | infty => exact hinfty
  | coe x => simpa [finitePoint] using h (WithTopology.ofTopology x)

private lemma latticeSeminormFamily_separating {A : Type*} [Uncountable A] (b : ℕ → A) :
    ∀ f : ContinuousFunctions A, f ≠ 0 →
      ∃ i, (latticeSeminormFamily b i).toSeminorm f ≠ 0 := by
  intro f hf
  obtain ⟨a, ha⟩ := exists_finitePoint_ne_zero hf
  by_cases hab : a ∈ Set.range b
  · obtain ⟨n, rfl⟩ := hab
    refine ⟨none, ?_⟩
    intro hq
    have hbounded : BddAbove (Set.range fun j => |f (finitePoint (b j))|) := by
      refine ⟨‖f‖, Set.forall_mem_range.mpr fun j => ?_⟩
      simpa [Real.norm_eq_abs] using ContinuousMap.norm_coe_le_norm f (finitePoint (b j))
    have hle : |f (finitePoint (b n))| ≤
        (uniformOnSequenceLatticeSeminorm b).toSeminorm f := by
      rw [uniformOnSequenceLatticeSeminorm_apply]
      exact le_ciSup hbounded n
    change (uniformOnSequenceLatticeSeminorm b).toSeminorm f = 0 at hq
    rw [hq] at hle
    exact ha (abs_eq_zero.mp (le_antisymm hle (abs_nonneg _)))
  · refine ⟨some ⟨a, hab⟩, ?_⟩
    simpa [latticeSeminormFamily, evaluationLatticeSeminorm_apply, abs_ne_zero] using ha

/-- The topology `τ` is Hausdorff. -/
theorem locallyConvexSolidTopology_t2Space {A : Type*} [Uncountable A] (b : ℕ → A) :
    @T2Space (ContinuousFunctions A) (locallyConvexSolidTopology b) := by
  letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
  letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
    isLocallyConvexSolidVectorLattice b
  letI : T1Space (ContinuousFunctions A) :=
    (withLatticeSeminorms b).T1_of_separating (latticeSeminormFamily_separating b)
  infer_instance

/-! ### The sigma-Lebesgue property -/

/-- The continuous function supported at the finite point `a`, with value `r` there. -/
noncomputable def pointMass {A : Type*} (a : A) (r : ℝ) : ContinuousFunctions A := by
  classical
  exact OnePoint.continuousMapMkDiscrete
    (fun x : WithDiscreteTopology A =>
      if WithTopology.ofTopology x = a then r else 0)
    0 (by
      refine tendsto_const_nhds.congr' ?_
      filter_upwards [Filter.eventually_cofinite_ne (WithTopology.toTopology ⊥ a)] with x hx
      rw [if_neg]
      intro h
      apply hx
      exact (WithTopology.toTopology_ofTopology (t := (⊥ : TopologicalSpace A)) x).symm.trans
        (congrArg (WithTopology.toTopology (⊥ : TopologicalSpace A)) h))

@[simp]
theorem pointMass_finitePoint {A : Type*} (a : A) (r : ℝ) :
    pointMass a r (finitePoint a) = r := by
  simp [pointMass, finitePoint, OnePoint.continuousMapMkDiscrete,
    OnePoint.continuousMapMk]

theorem pointMass_finitePoint_of_ne {A : Type*} {a c : A} (hca : c ≠ a) (r : ℝ) :
    pointMass a r (finitePoint c) = 0 := by
  simp [pointMass, finitePoint, OnePoint.continuousMapMkDiscrete,
    OnePoint.continuousMapMk, hca]

@[simp]
theorem pointMass_infty {A : Type*} (a : A) (r : ℝ) :
    pointMass a r (OnePoint.infty : AInfty A) = 0 := by
  simp [pointMass, OnePoint.continuousMapMkDiscrete, OnePoint.continuousMapMk]

lemma pointMass_le {A : Type*} {f : ContinuousFunctions A} (hf : 0 ≤ f)
    {a : A} {r : ℝ} (hr : r ≤ f (finitePoint a)) : pointMass a r ≤ f := by
  rw [ContinuousMap.le_def]
  intro x
  induction x using OnePoint.rec with
  | infty =>
      simpa using ContinuousMap.le_def.mp hf (OnePoint.infty : AInfty A)
  | coe x =>
      by_cases hxa : WithTopology.ofTopology x = a
      · have hx : x = WithTopology.toTopology ⊥ a :=
          (WithTopology.toTopology_ofTopology (t := (⊥ : TopologicalSpace A)) x).symm.trans
            (congrArg (WithTopology.toTopology (⊥ : TopologicalSpace A)) hxa)
        subst x
        simpa [pointMass, finitePoint, OnePoint.continuousMapMkDiscrete,
          OnePoint.continuousMapMk] using hr
      · simpa [pointMass, OnePoint.continuousMapMkDiscrete,
          OnePoint.continuousMapMk, hxa] using
          ContinuousMap.le_def.mp hf (x : AInfty A)

lemma isGLB_eval_finitePoint {A : Type*} {u : ℕ → ContinuousFunctions A}
    (hu_nonneg : ∀ n, 0 ≤ u n) (hu_glb : IsGLB (Set.range u) 0) (a : A) :
    IsGLB (Set.range fun n => u n (finitePoint a)) 0 := by
  constructor
  · rintro _ ⟨n, rfl⟩
    exact ContinuousMap.le_def.mp (hu_nonneg n) (finitePoint a)
  · intro r hr
    have hm : pointMass a r ∈ lowerBounds (Set.range u) := by
      rintro _ ⟨n, rfl⟩
      apply pointMass_le (hu_nonneg n)
      exact hr ⟨n, rfl⟩
    have hm0 := ContinuousMap.le_def.mp (hu_glb.2 hm) (finitePoint a)
    simpa using hm0

lemma tendsto_eval_finitePoint {A : Type*} {u : ℕ → ContinuousFunctions A}
    (hu_anti : Antitone u) (hu_nonneg : ∀ n, 0 ≤ u n)
    (hu_glb : IsGLB (Set.range u) 0) (a : A) :
    Filter.Tendsto (fun n => u n (finitePoint a)) Filter.atTop (nhds 0) := by
  exact tendsto_atTop_isGLB
    (fun _ _ hmn => ContinuousMap.le_def.mp (hu_anti hmn) (finitePoint a))
    (isGLB_eval_finitePoint hu_nonneg hu_glb a)

lemma isGLB_eval_infty {A : Type*} [Uncountable A] {u : ℕ → ContinuousFunctions A}
    (hu_nonneg : ∀ n, 0 ≤ u n) (hu_glb : IsGLB (Set.range u) 0) :
    IsGLB (Set.range fun n => u n (OnePoint.infty : AInfty A)) 0 := by
  constructor
  · rintro _ ⟨n, rfl⟩
    exact ContinuousMap.le_def.mp (hu_nonneg n) OnePoint.infty
  · intro r hr
    by_contra hr_nonpos
    have hr_pos : 0 < r := lt_of_not_ge hr_nonpos
    let bad : ℕ → Set A := fun n => {a | ¬r / 2 < u n (finitePoint a)}
    have hbad_finite : ∀ n, (bad n).Finite := by
      intro n
      have htend : Filter.Tendsto
          (fun x : WithDiscreteTopology A => u n (x : AInfty A)) Filter.cofinite
          (nhds (u n (OnePoint.infty : AInfty A))) :=
        (OnePoint.continuous_iff_from_discrete _).mp (u n).continuous
      have hlt : r / 2 < u n (OnePoint.infty : AInfty A) := by
        linarith [hr ⟨n, rfl⟩]
      have hev : ∀ᶠ x : WithDiscreteTopology A in Filter.cofinite,
          r / 2 < u n (x : AInfty A) := htend.eventually_const_lt hlt
      have hfinite : ({x : WithDiscreteTopology A |
          ¬r / 2 < u n (x : AInfty A)} : Set _).Finite :=
        Filter.eventually_cofinite.mp hev
      simpa [bad, finitePoint] using hfinite.preimage
        (WithTopology.toTopology_injective (⊥ : TopologicalSpace A)).injOn
    have hcount : (⋃ n, bad n).Countable :=
      Set.countable_iUnion fun n => (hbad_finite n).countable
    have hne : (⋃ n, bad n) ≠ (Set.univ : Set A) := by
      intro heq
      apply Set.not_countable_univ (α := A)
      rwa [← heq]
    obtain ⟨a, ha⟩ := (Set.ne_univ_iff_exists_notMem _).mp hne
    have hgood (n : ℕ) : r / 2 < u n (finitePoint a) := by
      by_contra h
      apply ha
      exact Set.mem_iUnion.2 ⟨n, by simpa [bad] using h⟩
    have hm : pointMass a (r / 2) ∈ lowerBounds (Set.range u) := by
      rintro _ ⟨n, rfl⟩
      exact pointMass_le (hu_nonneg n) (hgood n).le
    have hm0 := ContinuousMap.le_def.mp (hu_glb.2 hm) (finitePoint a)
    rw [pointMass_finitePoint] at hm0
    have hm0' : r / 2 ≤ 0 := by simpa using hm0
    linarith

lemma tendsto_eval_infty {A : Type*} [Uncountable A] {u : ℕ → ContinuousFunctions A}
    (hu_anti : Antitone u) (hu_nonneg : ∀ n, 0 ≤ u n)
    (hu_glb : IsGLB (Set.range u) 0) :
    Filter.Tendsto (fun n => u n (OnePoint.infty : AInfty A))
      Filter.atTop (nhds 0) := by
  exact tendsto_atTop_isGLB
    (fun _ _ hmn => ContinuousMap.le_def.mp (hu_anti hmn) OnePoint.infty)
    (isGLB_eval_infty hu_nonneg hu_glb)

/-- An order-decreasing sequence with infimum zero converges pointwise to zero. -/
lemma tendsto_eval {A : Type*} [Uncountable A] {u : ℕ → ContinuousFunctions A}
    (hu_anti : Antitone u) (hu_nonneg : ∀ n, 0 ≤ u n)
    (hu_glb : IsGLB (Set.range u) 0) (x : AInfty A) :
    Filter.Tendsto (fun n => u n x) Filter.atTop (nhds 0) := by
  induction x using OnePoint.rec with
  | infty => exact tendsto_eval_infty hu_anti hu_nonneg hu_glb
  | coe x =>
      simpa [finitePoint] using
        tendsto_eval_finitePoint hu_anti hu_nonneg hu_glb (WithTopology.ofTopology x)

/-- Dini's theorem upgrades pointwise order convergence to uniform convergence. -/
lemma tendsto_norm {A : Type*} [Uncountable A] {u : ℕ → ContinuousFunctions A}
    (hu_anti : Antitone u) (hu_nonneg : ∀ n, 0 ≤ u n)
    (hu_glb : IsGLB (Set.range u) 0) :
    Filter.Tendsto (fun n => ‖u n‖) Filter.atTop (nhds 0) := by
  have hu_uniform : Filter.Tendsto u Filter.atTop (nhds 0) :=
    ContinuousMap.tendsto_of_antitone_of_pointwise hu_anti
      (fun x => tendsto_eval hu_anti hu_nonneg hu_glb x)
  simpa using (continuous_norm.tendsto 0).comp hu_uniform

lemma uniformOnSequenceLatticeSeminorm_le_norm {A : Type*} (b : ℕ → A)
    (f : ContinuousFunctions A) :
    (uniformOnSequenceLatticeSeminorm b).toSeminorm f ≤ ‖f‖ := by
  rw [uniformOnSequenceLatticeSeminorm_apply]
  refine ciSup_le fun n => ?_
  simpa [Real.norm_eq_abs] using ContinuousMap.norm_coe_le_norm f (finitePoint (b n))

/-- Every defining seminorm of `τ` is bounded by the uniform norm. -/
lemma latticeSeminormFamily_le_norm {A : Type*} (b : ℕ → A) (i : SeminormIndex b)
    (f : ContinuousFunctions A) : (latticeSeminormFamily b i).toSeminorm f ≤ ‖f‖ := by
  cases i with
  | none => exact uniformOnSequenceLatticeSeminorm_le_norm b f
  | some a =>
      simpa [latticeSeminormFamily, evaluationLatticeSeminorm_apply, Real.norm_eq_abs] using
        ContinuousMap.norm_coe_le_norm f (finitePoint a.1)

/-- Lemma 2.3: the locally convex-solid topology `τ` has the sigma-Lebesgue property. -/
theorem lemma2_3 {A : Type*} [Uncountable A] (b : ℕ → A) :
    @IsSigmaLebesgueTopology (ContinuousFunctions A) _ _
      (locallyConvexSolidTopology b) := by
  letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
  letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
    isLocallyConvexSolidVectorLattice b
  constructor
  intro u hu_anti hu_nonneg hu_glb
  have hnorm := tendsto_norm hu_anti hu_nonneg hu_glb
  rw [(withLatticeSeminorms b).tendsto_nhds_atTop u 0]
  intro i ε hε
  have hev : ∀ᶠ n in Filter.atTop, ‖u n‖ < ε :=
    (tendsto_order.1 hnorm).2 ε hε
  obtain ⟨N, hN⟩ := Filter.eventually_atTop.1 hev
  refine ⟨N, fun n hn => ?_⟩
  simpa using (latticeSeminormFamily_le_norm b i (u n)).trans_lt (hN n hn)

/-! ### The completion -/

/-- The Banach lattice `c` of convergent real sequences, represented as continuous functions on
the one-point compactification of `ℕ`. -/
abbrev ConvergentSequences := C(OnePoint ℕ, ℝ)

/-- The space `c × ℝᴬʹ` appearing in Lemma 2.4. It carries the product of the uniform
topology on `c` and the topology of pointwise convergence on `ℝᴬʹ`. -/
abbrev CompletionSpace {A : Type*} (b : ℕ → A) :=
  ConvergentSequences × (OutsideSequence b → ℝ)

instance instIsOrderedAddMonoidCompletionSpace {A : Type*} (b : ℕ → A) :
    IsOrderedAddMonoid (CompletionSpace b) where
  add_le_add_left _ _ h z :=
    ⟨add_le_add_left h.1 z.1, add_le_add_left h.2 z.2⟩
  add_le_add_right _ _ h z :=
    ⟨add_le_add_right h.1 z.1, add_le_add_right h.2 z.2⟩

noncomputable instance instVectorLatticeCompletionSpace {A : Type*} (b : ℕ → A) :
    VectorLattice (CompletionSpace b) where
  smul_le_smul_of_nonneg_left _ ha _ _ h :=
    ⟨smul_le_smul_of_nonneg_left h.1 ha, smul_le_smul_of_nonneg_left h.2 ha⟩

/-- The convergent sequence obtained by restricting `f ∈ C(A∞)` to the distinguished
sequence `b`. -/
noncomputable def sequenceRestriction {A : Type*} (b : ℕ → A)
    (hb : Function.Injective b) (f : ContinuousFunctions A) : ConvergentSequences := by
  apply OnePoint.continuousMapMkNat
    (fun n => f (finitePoint (b n))) (f (OnePoint.infty : AInfty A))
  have htend : Filter.Tendsto
      (fun x : WithDiscreteTopology A => f (x : AInfty A)) Filter.cofinite
      (nhds (f (OnePoint.infty : AInfty A))) :=
    (OnePoint.continuous_iff_from_discrete _).mp f.continuous
  apply htend.comp
  simpa [Nat.cofinite_eq_atTop] using
    ((WithTopology.toTopology_injective (⊥ : TopologicalSpace A)).comp hb).tendsto_cofinite

/-- The map `J(f) = ((f(bⱼ))ⱼ, (f(a))ₐ∈ᴬʹ)` from Lemma 2.4. -/
noncomputable def completionEmbedding {A : Type*} (b : ℕ → A)
    (hb : Function.Injective b) (f : ContinuousFunctions A) : CompletionSpace b :=
  (sequenceRestriction b hb f, fun a => f (finitePoint a.1))

@[simp]
theorem sequenceRestriction_nat {A : Type*} (b : ℕ → A) (hb : Function.Injective b)
    (f : ContinuousFunctions A) (n : ℕ) :
    sequenceRestriction b hb f (n : OnePoint ℕ) = f (finitePoint (b n)) := by
  simp [sequenceRestriction, OnePoint.continuousMapMkNat, OnePoint.continuousMapMkDiscrete,
    OnePoint.continuousMapMk]

@[simp]
theorem sequenceRestriction_infty {A : Type*} (b : ℕ → A) (hb : Function.Injective b)
    (f : ContinuousFunctions A) :
    sequenceRestriction b hb f (OnePoint.infty : OnePoint ℕ) =
      f (OnePoint.infty : AInfty A) := by
  simp [sequenceRestriction, OnePoint.continuousMapMkNat, OnePoint.continuousMapMkDiscrete,
    OnePoint.continuousMapMk]

@[simp]
theorem completionEmbedding_fst {A : Type*} (b : ℕ → A) (hb : Function.Injective b)
    (f : ContinuousFunctions A) : (completionEmbedding b hb f).1 = sequenceRestriction b hb f :=
  rfl

@[simp]
theorem completionEmbedding_snd {A : Type*} (b : ℕ → A) (hb : Function.Injective b)
    (f : ContinuousFunctions A) (a : OutsideSequence b) :
    (completionEmbedding b hb f).2 a = f (finitePoint a.1) := rfl

/-- `J` as a vector lattice homomorphism. -/
noncomputable def completionEmbeddingVecLatHom {A : Type*} (b : ℕ → A)
    (hb : Function.Injective b) :
    VecLatHom (ContinuousFunctions A) (CompletionSpace b) where
  toFun := completionEmbedding b hb
  map_add' := by
    intro f g
    apply Prod.ext
    · ext x
      induction x using OnePoint.rec <;> simp
    · funext a
      rfl
  map_smul' := by
    intro r f
    apply Prod.ext
    · ext x
      induction x using OnePoint.rec <;> simp
    · funext a
      rfl
  map_sup' := by
    intro f g
    apply Prod.ext
    · ext x
      induction x using OnePoint.rec <;> simp
    · funext a
      rfl
  map_inf' := by
    intro f g
    apply Prod.ext
    · ext x
      induction x using OnePoint.rec <;> simp
    · funext a
      rfl

theorem completionEmbedding_injective {A : Type*} (b : ℕ → A)
    (hb : Function.Injective b) : Function.Injective (completionEmbedding b hb) := by
  intro f g hfg
  have hinfty : f (OnePoint.infty : AInfty A) = g (OnePoint.infty : AInfty A) := by
    have h := congrArg (fun y : CompletionSpace b => y.1 OnePoint.infty) hfg
    simpa using h
  have hfinite (a : A) : f (finitePoint a) = g (finitePoint a) := by
    by_cases ha : a ∈ Set.range b
    · obtain ⟨n, rfl⟩ := ha
      have h := congrArg (fun y : CompletionSpace b => y.1 (n : OnePoint ℕ)) hfg
      simpa using h
    · have h := congrArg (fun y : CompletionSpace b => y.2 ⟨a, ha⟩) hfg
      simpa using h
  ext x
  induction x using OnePoint.rec with
  | infty => exact hinfty
  | coe x => simpa [finitePoint] using hfinite (WithTopology.ofTopology x)

/-- Extend a convergent sequence from `range b` to `A∞`, taking its limit at all other
finite points. -/
noncomputable def extendConvergentSequence {A : Type*} (b : ℕ → A)
    (g : ConvergentSequences) : ContinuousFunctions A := by
  classical
  refine OnePoint.continuousMapMkDiscrete
    (fun x : WithDiscreteTopology A =>
      if h : WithTopology.ofTopology x ∈ Set.range b then
        g ((Classical.choose h : ℕ) : OnePoint ℕ)
      else g (OnePoint.infty : OnePoint ℕ))
    (g (OnePoint.infty : OnePoint ℕ)) ?_
  have hg : Filter.Tendsto (fun n : ℕ => g (n : OnePoint ℕ)) Filter.atTop
      (nhds (g (OnePoint.infty : OnePoint ℕ))) :=
    (OnePoint.continuous_iff_from_nat g).mp g.continuous
  intro U hU
  obtain ⟨N, hN⟩ := Filter.eventually_atTop.1 (hg hU)
  have hexclude : ∀ᶠ x : WithDiscreteTopology A in Filter.cofinite,
      ∀ n ∈ Finset.range N, x ≠ WithTopology.toTopology ⊥ (b n) :=
    (Finset.range N).eventually_all.2 fun n _ =>
      Filter.eventually_cofinite_ne (WithTopology.toTopology ⊥ (b n))
  change ∀ᶠ x : WithDiscreteTopology A in Filter.cofinite,
    (if h : WithTopology.ofTopology x ∈ Set.range b then
      g ((Classical.choose h : ℕ) : OnePoint ℕ)
    else g (OnePoint.infty : OnePoint ℕ)) ∈ U
  filter_upwards [hexclude] with x hx
  split_ifs with hxb
  · apply hN
    by_contra hn
    have hnN : Classical.choose hxb ∈ Finset.range N := Finset.mem_range.2 (Nat.lt_of_not_ge hn)
    apply hx (Classical.choose hxb) hnN
    exact congrArg (WithTopology.toTopology (⊥ : TopologicalSpace A))
      (Classical.choose_spec hxb).symm
  · exact mem_of_mem_nhds hU

@[simp]
theorem extendConvergentSequence_infty {A : Type*} (b : ℕ → A)
    (g : ConvergentSequences) :
    extendConvergentSequence b g (OnePoint.infty : AInfty A) =
      g (OnePoint.infty : OnePoint ℕ) := by
  simp [extendConvergentSequence, OnePoint.continuousMapMkDiscrete,
    OnePoint.continuousMapMk]

@[simp]
theorem extendConvergentSequence_b {A : Type*} (b : ℕ → A)
    (hb : Function.Injective b) (g : ConvergentSequences) (n : ℕ) :
    extendConvergentSequence b g (finitePoint (b n)) = g (n : OnePoint ℕ) := by
  classical
  change (if h : b n ∈ Set.range b then g ((Classical.choose h : ℕ) : OnePoint ℕ)
    else g (OnePoint.infty : OnePoint ℕ)) = g (n : OnePoint ℕ)
  rw [dif_pos ⟨n, rfl⟩]
  congr 1
  exact congrArg (fun k : ℕ => (k : OnePoint ℕ))
    (hb (Classical.choose_spec (⟨n, rfl⟩ : b n ∈ Set.range b)))

lemma pointMass_outside_at_b {A : Type*} (b : ℕ → A) (a : OutsideSequence b)
    (n : ℕ) (r : ℝ) : pointMass a.1 r (finitePoint (b n)) = 0 := by
  apply pointMass_finitePoint_of_ne
  intro h
  exact a.2 ⟨n, h⟩

/-- A continuous function matching a prescribed convergent sequence and prescribed values at a
finite set of points outside `range b`. -/
noncomputable def completionApproximation {A : Type*} (b : ℕ → A)
    (y : CompletionSpace b) (s : Finset (OutsideSequence b)) : ContinuousFunctions A :=
  extendConvergentSequence b y.1 +
    ∑ a ∈ s, pointMass a.1 (y.2 a - extendConvergentSequence b y.1 (finitePoint a.1))

@[simp]
theorem completionApproximation_b {A : Type*} (b : ℕ → A)
    (hb : Function.Injective b) (y : CompletionSpace b) (s : Finset (OutsideSequence b))
    (n : ℕ) : completionApproximation b y s (finitePoint (b n)) = y.1 (n : OnePoint ℕ) := by
  simp [completionApproximation, extendConvergentSequence_b b hb,
    pointMass_outside_at_b]

@[simp]
theorem completionApproximation_infty {A : Type*} (b : ℕ → A)
    (y : CompletionSpace b) (s : Finset (OutsideSequence b)) :
    completionApproximation b y s (OnePoint.infty : AInfty A) =
      y.1 (OnePoint.infty : OnePoint ℕ) := by
  simp [completionApproximation]

@[simp]
theorem completionApproximation_outside {A : Type*} (b : ℕ → A)
    (y : CompletionSpace b) (s : Finset (OutsideSequence b))
    (a : OutsideSequence b) (ha : a ∈ s) :
    completionApproximation b y s (finitePoint a.1) = y.2 a := by
  classical
  rw [completionApproximation]
  change evaluationLinearMap (finitePoint a.1)
    (extendConvergentSequence b y.1 +
      ∑ c ∈ s, pointMass c.1
        (y.2 c - extendConvergentSequence b y.1 (finitePoint c.1))) = y.2 a
  rw [map_add, map_sum]
  rw [Finset.sum_eq_single a]
  · simp [evaluationLinearMap]
  · intro c hc hca
    change pointMass c.1
      (y.2 c - extendConvergentSequence b y.1 (finitePoint c.1)) (finitePoint a.1) = 0
    apply pointMass_finitePoint_of_ne
    intro hac
    apply hca
    exact Subtype.ext hac.symm
  · intro hnot
    exact (hnot ha).elim

@[simp]
theorem sequenceRestriction_completionApproximation {A : Type*} (b : ℕ → A)
    (hb : Function.Injective b) (y : CompletionSpace b) (s : Finset (OutsideSequence b)) :
    sequenceRestriction b hb (completionApproximation b y s) = y.1 := by
  ext x
  induction x using OnePoint.rec with
  | infty => exact completionApproximation_infty b y s
  | coe n => exact completionApproximation_b b hb y s n

theorem completionEmbedding_denseRange {A : Type*} (b : ℕ → A)
    (hb : Function.Injective b) : DenseRange (completionEmbedding b hb) := by
  intro y
  rw [mem_closure_iff_nhds]
  intro U hU
  rcases mem_nhds_prod_iff.mp hU with ⟨u, hu, v, hv, huv⟩
  rw [nhds_pi] at hv
  rcases Filter.mem_pi'.mp hv with ⟨s, t, ht, htv⟩
  let f := completionApproximation b y s
  have hfirst : (completionEmbedding b hb f).1 ∈ u := by
    rw [completionEmbedding_fst, sequenceRestriction_completionApproximation]
    exact mem_of_mem_nhds hu
  have hsecond : (completionEmbedding b hb f).2 ∈ v := by
    apply htv
    intro a ha
    rw [completionEmbedding_snd, completionApproximation_outside b y s a
      (Finset.mem_coe.mp ha)]
    exact mem_of_mem_nhds (ht a)
  exact ⟨completionEmbedding b hb f, huv ⟨hfirst, hsecond⟩, ⟨f, rfl⟩⟩

theorem norm_sequenceRestriction {A : Type*} (b : ℕ → A)
    (hb : Function.Injective b) (f : ContinuousFunctions A) :
    ‖sequenceRestriction b hb f‖ = (uniformOnSequenceLatticeSeminorm b).toSeminorm f := by
  apply le_antisymm
  · apply (ContinuousMap.norm_le (sequenceRestriction b hb f)
      (apply_nonneg (uniformOnSequenceLatticeSeminorm b).toSeminorm f)).2
    intro x
    induction x using OnePoint.rec with
    | coe n =>
        rw [sequenceRestriction_nat, Real.norm_eq_abs,
          uniformOnSequenceLatticeSeminorm_apply]
        exact le_ciSup
          ⟨‖f‖, Set.forall_mem_range.mpr fun j => by
            simpa [Real.norm_eq_abs] using
              ContinuousMap.norm_coe_le_norm f (finitePoint (b j))⟩ n
    | infty =>
        rw [sequenceRestriction_infty, Real.norm_eq_abs]
        have hlim : Filter.Tendsto (fun n => |f (finitePoint (b n))|) Filter.atTop
            (nhds |f (OnePoint.infty : AInfty A)|) := by
          simpa using (continuous_abs.tendsto
            (f (OnePoint.infty : AInfty A))).comp
              ((OnePoint.continuous_iff_from_nat (sequenceRestriction b hb f)).mp
                (sequenceRestriction b hb f).continuous)
        apply le_of_tendsto' hlim
        intro n
        rw [uniformOnSequenceLatticeSeminorm_apply]
        exact le_ciSup
          ⟨‖f‖, Set.forall_mem_range.mpr fun j => by
            simpa [Real.norm_eq_abs] using
              ContinuousMap.norm_coe_le_norm f (finitePoint (b j))⟩ n
  · rw [uniformOnSequenceLatticeSeminorm_apply]
    refine ciSup_le fun n => ?_
    simpa [Real.norm_eq_abs] using
      ContinuousMap.norm_coe_le_norm (sequenceRestriction b hb f) (n : OnePoint ℕ)

theorem completionEmbedding_isInducing {A : Type*} [Uncountable A] (b : ℕ → A)
    (hb : Function.Injective b) :
    @Topology.IsInducing (ContinuousFunctions A) (CompletionSpace b)
      (locallyConvexSolidTopology b) inferInstance (completionEmbedding b hb) := by
  letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
  letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
    isLocallyConvexSolidVectorLattice b
  let J := (completionEmbeddingVecLatHom b hb).toLinearMap.toAddMonoidHom
  change Topology.IsInducing (J : ContinuousFunctions A → CompletionSpace b)
  apply IsTopologicalAddGroup.isInducing_iff_nhds_zero.mpr
  change nhds (0 : ContinuousFunctions A) =
    Filter.comap (completionEmbedding b hb) (nhds (0 : CompletionSpace b))
  have hp : WithSeminorms
      (LatticeSeminorm.toSeminormFamily (latticeSeminormFamily b)) :=
    withLatticeSeminorms b
  have hsource := (SeminormFamily.withSeminorms_iff_nhds_eq_iInf
    (p := LatticeSeminorm.toSeminormFamily (latticeSeminormFamily b))).mp hp
  rw [hsource]
  rw [nhds_prod_eq, Filter.comap_prod]
  change (⨅ i, Filter.comap
      (⇑(LatticeSeminorm.toSeminormFamily (latticeSeminormFamily b) i)) (nhds 0)) =
    Filter.comap (Prod.fst ∘ completionEmbedding b hb) (nhds (0 : ConvergentSequences)) ⊓
      Filter.comap (Prod.snd ∘ completionEmbedding b hb)
        (nhds (0 : OutsideSequence b → ℝ))
  rw [← @comap_norm_nhds_zero ConvergentSequences _]
  rw [nhds_pi]
  simp only [Filter.pi, Filter.comap_iInf, Filter.comap_comap]
  rw [iInf_option]
  have hfirst :
      Filter.comap
          (⇑(LatticeSeminorm.toSeminormFamily (latticeSeminormFamily b) none)) (nhds 0) =
        Filter.comap (norm ∘ Prod.fst ∘ completionEmbedding b hb) (nhds 0) := by
    congr 1
    funext f
    exact (norm_sequenceRestriction b hb f).symm
  have hcoord (a : OutsideSequence b) :
      Filter.comap
          (⇑(LatticeSeminorm.toSeminormFamily (latticeSeminormFamily b) (some a))) (nhds 0) =
        Filter.comap (Function.eval a ∘ Prod.snd ∘ completionEmbedding b hb) (nhds 0) := by
    calc
      _ = Filter.comap
          (norm ∘ Function.eval a ∘ Prod.snd ∘ completionEmbedding b hb) (nhds 0) := by
            congr 1
      _ = Filter.comap (Function.eval a ∘ Prod.snd ∘ completionEmbedding b hb)
          (Filter.comap norm (nhds 0)) := by rw [Filter.comap_comap]
      _ = Filter.comap (Function.eval a ∘ Prod.snd ∘ completionEmbedding b hb)
          (nhds 0) := by rw [comap_norm_nhds_zero]
  rw [hfirst, iInf_congr hcoord]
  simp

section CompletionPackage

variable {A : Type*} [Uncountable A] (b : ℕ → A) (hb : Function.Injective b)

/-- The canonical additive-group uniformity associated to the topology `τ`. -/
@[implicit_reducible]
noncomputable def locallyConvexSolidUniformSpace : UniformSpace (ContinuousFunctions A) := by
  letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
  letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
    isLocallyConvexSolidVectorLattice b
  exact IsTopologicalAddGroup.rightUniformSpace (ContinuousFunctions A)

/-- The natural product `c × ℝᴬʹ`, together with `J`, as an abstract completion of
`(C(A∞), τ)`. -/
noncomputable def completionPackage :
    @AbstractCompletion (ContinuousFunctions A) (locallyConvexSolidUniformSpace b) := by
  letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
  letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
    isLocallyConvexSolidVectorLattice b
  letI : T2Space (ContinuousFunctions A) := locallyConvexSolidTopology_t2Space b
  letI : UniformSpace (ContinuousFunctions A) := locallyConvexSolidUniformSpace b
  letI : IsUniformAddGroup (ContinuousFunctions A) := isUniformAddGroup_of_addCommGroup
  exact
    { space := CompletionSpace b
      coe := completionEmbedding b hb
      uniformStruct := inferInstance
      complete := inferInstance
      separation := inferInstance
      isUniformInducing := by
        let J := (completionEmbeddingVecLatHom b hb).toLinearMap.toAddMonoidHom
        change IsUniformInducing (J : ContinuousFunctions A → CompletionSpace b)
        exact AddMonoidHom.isUniformInducing_of_isInducing (completionEmbedding_isInducing b hb)
      dense := completionEmbedding_denseRange b hb }

/-- The uniform equivalence from the concrete completion to mathlib's canonical completion. -/
noncomputable def completionEquiv :
    CompletionSpace b ≃ᵤ
      @UniformSpace.Completion (ContinuousFunctions A) (locallyConvexSolidUniformSpace b) :=
  @AbstractCompletion.compareEquiv (ContinuousFunctions A) (locallyConvexSolidUniformSpace b)
    (completionPackage b hb)
    (@UniformSpace.Completion.cPkg (ContinuousFunctions A) (locallyConvexSolidUniformSpace b))

@[simp]
theorem completionEquiv_completionEmbedding (f : ContinuousFunctions A) :
    completionEquiv b hb (completionEmbedding b hb f) =
      (f : @UniformSpace.Completion (ContinuousFunctions A)
        (locallyConvexSolidUniformSpace b)) := by
  exact @AbstractCompletion.compare_coe (ContinuousFunctions A)
    (locallyConvexSolidUniformSpace b) (completionPackage b hb)
    (@UniformSpace.Completion.cPkg (ContinuousFunctions A) (locallyConvexSolidUniformSpace b)) f

/-- Lemma 2.4: `c × ℝᴬʹ`, with the map `J`, is the completion of `(C(A∞), τ)`. -/
theorem lemma2_4 :
    ∃ e : CompletionSpace b ≃ᵤ
        @UniformSpace.Completion (ContinuousFunctions A) (locallyConvexSolidUniformSpace b),
      ∀ f : ContinuousFunctions A,
        e (completionEmbedding b hb f) =
          (f : @UniformSpace.Completion (ContinuousFunctions A)
            (locallyConvexSolidUniformSpace b)) := by
  exact ⟨completionEquiv b hb, completionEquiv_completionEmbedding b hb⟩

end CompletionPackage

/-! ### Failure of the sigma-Lebesgue property in the completion -/

/-- The convergent sequence whose first `n` entries are zero and whose remaining entries are one. -/
noncomputable def convergentTail (n : ℕ) : ConvergentSequences := by
  apply OnePoint.continuousMapMkNat (fun j => if j < n then 0 else 1) 1
  refine tendsto_const_nhds.congr' ?_
  filter_upwards [Filter.eventually_ge_atTop n] with j hj
  simp [Nat.not_lt.mpr hj]

@[simp]
theorem convergentTail_nat (n j : ℕ) :
    convergentTail n (j : OnePoint ℕ) = if j < n then 0 else 1 := by
  simp [convergentTail, OnePoint.continuousMapMkNat, OnePoint.continuousMapMkDiscrete,
    OnePoint.continuousMapMk]

@[simp]
theorem convergentTail_infty (n : ℕ) :
    convergentTail n (OnePoint.infty : OnePoint ℕ) = 1 := by
  simp [convergentTail, OnePoint.continuousMapMkNat, OnePoint.continuousMapMkDiscrete,
    OnePoint.continuousMapMk]

/-- The sequence `(xₙ, 0)` from the final paragraph of the proof. -/
noncomputable def completionTail {A : Type*} (b : ℕ → A) (n : ℕ) : CompletionSpace b :=
  (convergentTail n, 0)

theorem completionTail_antitone {A : Type*} (b : ℕ → A) : Antitone (completionTail b) := by
  intro m n hmn
  constructor
  · rw [ContinuousMap.le_def]
    intro x
    induction x using OnePoint.rec with
    | infty => simp [completionTail]
    | coe j =>
        simp only [completionTail, convergentTail_nat]
        split_ifs <;> norm_num; omega
  · exact le_rfl

theorem completionTail_nonneg {A : Type*} (b : ℕ → A) (n : ℕ) :
    0 ≤ completionTail b n := by
  constructor
  · rw [ContinuousMap.le_def]
    intro x
    induction x using OnePoint.rec with
    | infty => simp [completionTail]
    | coe j =>
        simp only [completionTail, convergentTail_nat]
        split_ifs <;> norm_num
  · exact le_rfl

theorem completionTail_isGLB {A : Type*} (b : ℕ → A) :
    IsGLB (Set.range (completionTail b)) 0 := by
  constructor
  · rintro _ ⟨n, rfl⟩
    exact completionTail_nonneg b n
  · intro y hy
    have hfinite (j : ℕ) : y.1 (j : OnePoint ℕ) ≤ 0 := by
      have h := (hy ⟨j + 1, rfl⟩).1
      exact ContinuousMap.le_def.mp h (j : OnePoint ℕ) |>.trans_eq (by
        simp [completionTail])
    have hinfty : y.1 (OnePoint.infty : OnePoint ℕ) ≤ 0 := by
      exact le_of_tendsto'
        ((OnePoint.continuous_iff_from_nat y.1).mp y.1.continuous) hfinite
    constructor
    · rw [ContinuousMap.le_def]
      intro x
      induction x using OnePoint.rec with
      | infty => exact hinfty
      | coe j => exact hfinite j
    · simpa [completionTail] using (hy ⟨0, rfl⟩).2

theorem completionTail_not_tendsto {A : Type*} (b : ℕ → A) :
    ¬Filter.Tendsto (completionTail b) Filter.atTop (nhds 0) := by
  intro h
  have hfirst : Filter.Tendsto (fun n => (completionTail b n).1) Filter.atTop (nhds 0) := by
    simpa using (continuous_fst.tendsto (0 : CompletionSpace b)).comp h
  have hinfty : Filter.Tendsto
      (fun n => (completionTail b n).1 (OnePoint.infty : OnePoint ℕ))
      Filter.atTop (nhds 0) := by
    simpa using ((continuous_eval_const (OnePoint.infty : OnePoint ℕ)).tendsto 0).comp hfirst
  have hone : Filter.Tendsto (fun _ : ℕ => (1 : ℝ)) Filter.atTop (nhds 0) :=
    hinfty.congr' (Filter.Eventually.of_forall fun n => by simp [completionTail])
  have hzero : (1 : ℝ) = 0 := tendsto_nhds_unique tendsto_const_nhds hone
  norm_num at hzero

theorem completionSpace_not_isSigmaLebesgueTopology {A : Type*} (b : ℕ → A) :
    ¬IsSigmaLebesgueTopology (CompletionSpace b) := by
  intro h
  exact completionTail_not_tendsto b
    (h.tendsto_of_antitone_isGLB_zero (completionTail_antitone b)
      (completionTail_nonneg b) (completionTail_isGLB b))

theorem completionEquiv_map_sup {A : Type*} [Uncountable A] (b : ℕ → A)
    (hb : Function.Injective b) :
    letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
    letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
      isLocallyConvexSolidVectorLattice b
    letI : T2Space (ContinuousFunctions A) := locallyConvexSolidTopology_t2Space b
    letI : UniformSpace (ContinuousFunctions A) := locallyConvexSolidUniformSpace b
    letI : IsUniformAddGroup (ContinuousFunctions A) := isUniformAddGroup_of_addCommGroup
    ∀ x y : CompletionSpace b,
      completionEquiv b hb (x ⊔ y) = completionEquiv b hb x ⊔ completionEquiv b hb y := by
  letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
  letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
    isLocallyConvexSolidVectorLattice b
  letI : T2Space (ContinuousFunctions A) := locallyConvexSolidTopology_t2Space b
  letI : UniformSpace (ContinuousFunctions A) := locallyConvexSolidUniformSpace b
  letI : IsUniformAddGroup (ContinuousFunctions A) := isUniformAddGroup_of_addCommGroup
  intro x y
  have hseqSup : Continuous
      (fun p : ConvergentSequences × ConvergentSequences => p.1 ⊔ p.2) :=
    NormedVectorLattice.continuous_sup
  have hspaceSup : Continuous
      (fun p : CompletionSpace b × CompletionSpace b => p.1 ⊔ p.2) := by
    apply Continuous.prodMk
    · exact hseqSup.comp
        ((continuous_fst.comp continuous_fst).prodMk (continuous_fst.comp continuous_snd))
    · apply continuous_pi
      intro a
      exact ((continuous_apply a).comp (continuous_snd.comp continuous_fst)).sup
        ((continuous_apply a).comp (continuous_snd.comp continuous_snd))
  have hcompletionSup : Continuous
      (fun p : (@UniformSpace.Completion (ContinuousFunctions A)
        (locallyConvexSolidUniformSpace b)) ×
          @UniformSpace.Completion (ContinuousFunctions A)
            (locallyConvexSolidUniformSpace b) => p.1 ⊔ p.2) :=
    ((isLocallySolidVectorLattice_iff_uniformContinuous_sup
      (E := @UniformSpace.Completion (ContinuousFunctions A)
        (locallyConvexSolidUniformSpace b))).mp inferInstance).continuous
  refine (completionEmbedding_denseRange b hb).induction_on₂ ?_ ?_ x y
  · exact isClosed_eq
      ((completionEquiv b hb).continuous.comp hspaceSup)
      (hcompletionSup.comp
        ((completionEquiv b hb).continuous.comp continuous_fst |>.prodMk
          ((completionEquiv b hb).continuous.comp continuous_snd)))
  · intro f g
    calc
      completionEquiv b hb
          (completionEmbedding b hb f ⊔ completionEmbedding b hb g) =
          completionEquiv b hb (completionEmbedding b hb (f ⊔ g)) :=
        congrArg (completionEquiv b hb)
          (map_sup (completionEmbeddingVecLatHom b hb) f g).symm
      _ = ((f ⊔ g : ContinuousFunctions A) :
          @UniformSpace.Completion (ContinuousFunctions A)
            (locallyConvexSolidUniformSpace b)) :=
        completionEquiv_completionEmbedding b hb (f ⊔ g)
      _ = (f : @UniformSpace.Completion (ContinuousFunctions A)
          (locallyConvexSolidUniformSpace b)) ⊔
          (g : @UniformSpace.Completion (ContinuousFunctions A)
            (locallyConvexSolidUniformSpace b)) :=
        map_sup (IsLocallySolidVectorLattice.toCompletionVecLatHom
          (E := ContinuousFunctions A)) f g
      _ = completionEquiv b hb (completionEmbedding b hb f) ⊔
          completionEquiv b hb (completionEmbedding b hb g) := by
        rw [completionEquiv_completionEmbedding, completionEquiv_completionEmbedding]

theorem completionEquiv_le_iff {A : Type*} [Uncountable A] (b : ℕ → A)
    (hb : Function.Injective b) :
    letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
    letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
      isLocallyConvexSolidVectorLattice b
    letI : T2Space (ContinuousFunctions A) := locallyConvexSolidTopology_t2Space b
    letI : UniformSpace (ContinuousFunctions A) := locallyConvexSolidUniformSpace b
    letI : IsUniformAddGroup (ContinuousFunctions A) := isUniformAddGroup_of_addCommGroup
    ∀ x y : CompletionSpace b,
      completionEquiv b hb x ≤ completionEquiv b hb y ↔ x ≤ y := by
  letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
  letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
    isLocallyConvexSolidVectorLattice b
  letI : T2Space (ContinuousFunctions A) := locallyConvexSolidTopology_t2Space b
  letI : UniformSpace (ContinuousFunctions A) := locallyConvexSolidUniformSpace b
  letI : IsUniformAddGroup (ContinuousFunctions A) := isUniformAddGroup_of_addCommGroup
  intro x y
  constructor
  · intro h
    rw [← sup_eq_right]
    apply (completionEquiv b hb).injective
    rw [completionEquiv_map_sup, sup_eq_right.mpr h]
  · intro h
    rw [← sup_eq_right]
    rw [← completionEquiv_map_sup, sup_eq_right.mpr h]

@[simp]
theorem completionEquiv_zero {A : Type*} [Uncountable A] (b : ℕ → A)
    (hb : Function.Injective b) :
    letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
    letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
      isLocallyConvexSolidVectorLattice b
    letI : T2Space (ContinuousFunctions A) := locallyConvexSolidTopology_t2Space b
    letI : UniformSpace (ContinuousFunctions A) := locallyConvexSolidUniformSpace b
    letI : IsUniformAddGroup (ContinuousFunctions A) := isUniformAddGroup_of_addCommGroup
    completionEquiv b hb 0 = 0 := by
  letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
  letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
    isLocallyConvexSolidVectorLattice b
  letI : T2Space (ContinuousFunctions A) := locallyConvexSolidTopology_t2Space b
  letI : UniformSpace (ContinuousFunctions A) := locallyConvexSolidUniformSpace b
  letI : IsUniformAddGroup (ContinuousFunctions A) := isUniformAddGroup_of_addCommGroup
  calc
    completionEquiv b hb 0 =
        completionEquiv b hb (completionEmbedding b hb 0) :=
      congrArg (completionEquiv b hb)
        (map_zero (completionEmbeddingVecLatHom b hb)).symm
    _ = ((0 : ContinuousFunctions A) :
        @UniformSpace.Completion (ContinuousFunctions A)
          (locallyConvexSolidUniformSpace b)) :=
      completionEquiv_completionEmbedding b hb 0
    _ = 0 := map_zero
      (IsLocallySolidVectorLattice.toCompletionVecLatHom
        (E := ContinuousFunctions A))

/-- The canonical completion inherits the concrete counterexample, so it is not
sigma-Lebesgue. -/
theorem completion_not_isSigmaLebesgueTopology {A : Type*} [Uncountable A]
    (b : ℕ → A) (hb : Function.Injective b) :
    letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
    letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
      isLocallyConvexSolidVectorLattice b
    letI : T2Space (ContinuousFunctions A) := locallyConvexSolidTopology_t2Space b
    letI : UniformSpace (ContinuousFunctions A) := locallyConvexSolidUniformSpace b
    letI : IsUniformAddGroup (ContinuousFunctions A) := isUniformAddGroup_of_addCommGroup
    ¬ IsSigmaLebesgueTopology (UniformSpace.Completion (ContinuousFunctions A)) := by
  letI : TopologicalSpace (ContinuousFunctions A) := locallyConvexSolidTopology b
  letI : IsLocallyConvexSolidVectorLattice (ContinuousFunctions A) :=
    isLocallyConvexSolidVectorLattice b
  letI : T2Space (ContinuousFunctions A) := locallyConvexSolidTopology_t2Space b
  letI : UniformSpace (ContinuousFunctions A) := locallyConvexSolidUniformSpace b
  letI : IsUniformAddGroup (ContinuousFunctions A) := isUniformAddGroup_of_addCommGroup
  intro hsigma
  let x : ℕ → UniformSpace.Completion (ContinuousFunctions A) :=
    fun n => completionEquiv b hb (completionTail b n)
  have hx_antitone : Antitone x := by
    intro m n hmn
    exact (completionEquiv_le_iff b hb _ _).2
      (completionTail_antitone b hmn)
  have hx_nonneg (n : ℕ) : 0 ≤ x n := by
    rw [← completionEquiv_zero b hb]
    exact (completionEquiv_le_iff b hb _ _).2 (completionTail_nonneg b n)
  have hx_isGLB : IsGLB (Set.range x) 0 := by
    constructor
    · rintro _ ⟨n, rfl⟩
      exact hx_nonneg n
    · intro z hz
      obtain ⟨y, rfl⟩ := (completionEquiv b hb).surjective z
      rw [← completionEquiv_zero b hb]
      apply (completionEquiv_le_iff b hb _ _).2
      apply (completionTail_isGLB b).2
      rintro _ ⟨n, rfl⟩
      exact (completionEquiv_le_iff b hb _ _).1 (hz ⟨n, rfl⟩)
  have hx_tendsto : Filter.Tendsto x Filter.atTop (nhds 0) :=
    hsigma.tendsto_of_antitone_isGLB_zero hx_antitone hx_nonneg hx_isGLB
  apply completionTail_not_tendsto b
  have hback := ((completionEquiv b hb).symm.continuous.tendsto
    (0 : UniformSpace.Completion (ContinuousFunctions A))).comp hx_tendsto
  have hinv_zero : (completionEquiv b hb).symm 0 = 0 := by
    apply (completionEquiv b hb).injective
    simp
  rw [hinv_zero] at hback
  apply hback.congr'
  exact Filter.Eventually.of_forall fun n => by simp [x]

/-- Theorem 2.5: there exists a Hausdorff sigma-Lebesgue locally convex-solid
vector lattice whose topological completion is not sigma-Lebesgue. -/
theorem theorem2_5 :
  ∃ (E : Type) (_ : AddCommGroup E) (_ : Lattice E)
    (_ : IsOrderedAddMonoid E) (_ : VectorLattice E)
    (_ : TopologicalSpace E) (_ : T2Space E)
    (_ : IsLocallyConvexSolidVectorLattice E),
    IsSigmaLebesgueTopology E ∧
      letI : UniformSpace E := IsTopologicalAddGroup.rightUniformSpace E
      letI : IsUniformAddGroup E := isUniformAddGroup_of_addCommGroup
      ¬ IsSigmaLebesgueTopology (UniformSpace.Completion E) := by
  let b : ℕ → ℝ := fun n => n
  have hb : Function.Injective b := Nat.cast_injective
  refine ⟨ContinuousFunctions ℝ, inferInstance, inferInstance, inferInstance,
    inferInstance, locallyConvexSolidTopology b,
    locallyConvexSolidTopology_t2Space b,
    isLocallyConvexSolidVectorLattice b, ?_⟩
  constructor
  · exact lemma2_3 b
  · exact completion_not_isSigmaLebesgueTopology b hb

end Aliprantis.Question1
