import BanLat.LocallySolid.Completion
import BanLat.LocallySolid.LocallyConvexSolid
import BanLat.LocallySolid.WithSeminorms
import BanLat.Examples.CofK.Basic
import BanLat.LLexpr
import BanLat.Substructures.Ideal
import Mathlib.Topology.Compactification.OnePoint.Basic
import Mathlib.Topology.Maps.Basic
import Mathlib.Topology.UniformSpace.Dini

open scoped Topology

namespace Aliprantis.Question2

variable (E : Type*) [AddCommGroup E] [Lattice E] [IsOrderedAddMonoid E]
  [VectorLattice E] [TopologicalSpace E] [IsLocallySolidVectorLattice E]

/-- A locally solid vector lattice has property `(B, i)` if every positive,
increasing, topologically bounded sequence is Cauchy. Here topological
boundedness is expressed as von Neumann boundedness, and Cauchyness uses the
canonical uniformity induced by the topological additive group. -/
class Bi : Prop where
  cauchySeq_of_monotone_nonneg_isVonNBounded :
    ∀ {u : ℕ → E}, Monotone u → (∀ n, 0 ≤ u n) →
      Bornology.IsVonNBounded ℝ (Set.range u) →
      letI : UniformSpace E := IsTopologicalAddGroup.rightUniformSpace E
      CauchySeq u

/-! ## The space from Section 3.2 -/

/-- The ambient realization of `c₀`: continuous functions on the one-point
compactification of `ℕ` whose value at infinity is zero. -/
noncomputable def c0Sublattice : VectorSublattice C(OnePoint ℕ, ℝ) where
  toSubmodule :=
    { carrier := {f | f (OnePoint.infty : OnePoint ℕ) = 0}
      zero_mem' := rfl
      add_mem' := by
        intro f g hf hg
        change f OnePoint.infty = 0 at hf
        change g OnePoint.infty = 0 at hg
        change f OnePoint.infty + g OnePoint.infty = 0
        rw [hf, hg, add_zero]
      smul_mem' := by
        intro r f hf
        change f OnePoint.infty = 0 at hf
        change r • f OnePoint.infty = 0
        rw [hf, smul_zero] }
  sup_mem' := by
    intro f g hf hg
    change f OnePoint.infty = 0 at hf
    change g OnePoint.infty = 0 at hg
    change max (f OnePoint.infty) (g OnePoint.infty) = 0
    rw [hf, hg, max_self]

/-- The Banach lattice `c₀`, represented as functions on `ℕ` converging to zero. -/
noncomputable abbrev C0 := c0Sublattice.toSubmodule

/-- The realization of `c₀` as functions vanishing at infinity is closed in
the Banach space of continuous functions on `OnePoint ℕ`. -/
theorem c0Sublattice_isClosed :
    IsClosed (c0Sublattice : Set C(OnePoint ℕ, ℝ)) := by
  change IsClosed {f : C(OnePoint ℕ, ℝ) |
    f (OnePoint.infty : OnePoint ℕ) = 0}
  exact isClosed_eq (continuous_eval_const _) continuous_const

/-- Elements of `C0` restrict to real sequences tending to zero. -/
theorem C0.tendsto_zero (f : C0) :
    Filter.Tendsto (fun n : ℕ => f.1 (n : OnePoint ℕ)) Filter.atTop (nhds 0) := by
  have h := (OnePoint.continuous_iff_from_nat f.1).mp f.1.continuous
  have hf : f.1 (OnePoint.infty : OnePoint ℕ) = 0 := f.2
  simpa [hf] using h

/-- The index set `P S = (ℝ₊)ℕ` from the paper. -/
abbrev PositiveSequences := ℕ → NNReal

/-- The complete ambient vector lattice `c₀ × ℝᴾˢ`. -/
noncomputable abbrev AmbientSpace := C0 × (PositiveSequences → ℝ)

instance instIsOrderedAddMonoidAmbientSpace : IsOrderedAddMonoid AmbientSpace where
  add_le_add_left _ _ h z :=
    ⟨add_le_add_left h.1 z.1, add_le_add_left h.2 z.2⟩
  add_le_add_right _ _ h z :=
    ⟨add_le_add_right h.1 z.1, add_le_add_right h.2 z.2⟩

noncomputable instance instVectorLatticeAmbientSpace : VectorLattice AmbientSpace where
  smul_le_smul_of_nonneg_left _ ha _ _ h :=
    ⟨smul_le_smul_of_nonneg_left h.1 ha, smul_le_smul_of_nonneg_left h.2 ha⟩

/-- The `j`th standard unit vector of `c₀`. -/
noncomputable def c0Unit (j : ℕ) : C0 := by
  refine ⟨OnePoint.continuousMapMkNat (fun m => if m = j then 1 else 0) 0 ?_, ?_⟩
  · refine tendsto_const_nhds.congr' ?_
    filter_upwards [Filter.eventually_gt_atTop j] with m hm
    simp [hm.ne']
  · change OnePoint.continuousMapMkNat (fun m => if m = j then 1 else 0) 0 _
        OnePoint.infty = 0
    simp [OnePoint.continuousMapMkNat, OnePoint.continuousMapMkDiscrete,
      OnePoint.continuousMapMk]

@[simp]
theorem c0Unit_apply (j m : ℕ) : (c0Unit j).1 (m : OnePoint ℕ) = if m = j then 1 else 0 := by
  simp [c0Unit, OnePoint.continuousMapMkNat, OnePoint.continuousMapMkDiscrete,
    OnePoint.continuousMapMk]

@[simp]
theorem c0Unit_infty (j : ℕ) :
    (c0Unit j).1 (OnePoint.infty : OnePoint ℕ) = 0 := by
  simp [c0Unit, OnePoint.continuousMapMkNat, OnePoint.continuousMapMkDiscrete,
    OnePoint.continuousMapMk]

/-- The generator `aⱼ = (eⱼ, fun α ↦ α(j))` from Section 3.2. -/
noncomputable def generator (j : ℕ) : AmbientSpace :=
  (c0Unit j, fun α => α j)

/-- The vector sublattice `Y` generated by the elements `aⱼ`. -/
noncomputable def Y : VectorSublattice AmbientSpace :=
  VectorSublattice.generated (Set.range generator)

theorem generator_mem_Y (j : ℕ) : generator j ∈ Y :=
  VectorSublattice.subset_generated (Set.range generator) ⟨j, rfl⟩

@[simp]
theorem generator_fst_apply (j m : ℕ) :
    (generator j).1.1 (m : OnePoint ℕ) = if m = j then 1 else 0 :=
  c0Unit_apply j m

@[simp]
theorem generator_snd_apply (j : ℕ) (α : PositiveSequences) :
    (generator j).2 α = α j :=
  rfl

noncomputable def ambientFstEvalAddHom (p : OnePoint ℕ) : AmbientSpace →+ ℝ where
  toFun x := x.1.1 p
  map_zero' := rfl
  map_add' _ _ := rfl

/-- The finite linear combination of the generators obtained by truncating
the `c₀` coordinate of `z` after `N` terms. -/
noncomputable def yApproximation (z : AmbientSpace) (N : ℕ) : AmbientSpace :=
  ∑ j ∈ Finset.range N, z.1.1 (j : OnePoint ℕ) • generator j

theorem yApproximation_mem_Y (z : AmbientSpace) (N : ℕ) :
    yApproximation z N ∈ Y := by
  apply Y.toSubmodule.sum_mem
  intro j hj
  exact Y.toSubmodule.smul_mem _ (generator_mem_Y j)

@[simp]
theorem yApproximation_fst_apply (z : AmbientSpace) (N m : ℕ) :
    (yApproximation z N).1.1 (m : OnePoint ℕ) =
      if m < N then z.1.1 (m : OnePoint ℕ) else 0 := by
  classical
  change ambientFstEvalAddHom (m : OnePoint ℕ) (yApproximation z N) = _
  rw [yApproximation, map_sum]
  by_cases hm : m < N <;>
    simp [ambientFstEvalAddHom, generator, c0Unit_apply, hm]

@[simp]
theorem yApproximation_fst_infty (z : AmbientSpace) (N : ℕ) :
    (yApproximation z N).1.1 (OnePoint.infty : OnePoint ℕ) = 0 := by
  change ambientFstEvalAddHom OnePoint.infty (yApproximation z N) = 0
  rw [yApproximation, map_sum]
  simp [ambientFstEvalAddHom, generator]

/-- The finitely supported correction used to match the prescribed second
coordinates indexed by `s`. -/
noncomputable def ambientCorrection (z : AmbientSpace)
    (s : Finset (Option PositiveSequences)) (N : ℕ) : PositiveSequences → ℝ := by
  classical
  exact fun α => if some α ∈ s then z.2 α - (yApproximation z N).2 α else 0

/-- An element of `X` which approximates `z`: its first coordinate is a
finite truncation, and its selected second coordinates agree exactly with
those of `z`. -/
noncomputable def ambientApproximation (z : AmbientSpace)
    (s : Finset (Option PositiveSequences)) (N : ℕ) : AmbientSpace :=
  yApproximation z N + (0, ambientCorrection z s N)

@[simp]
theorem ambientApproximation_fst (z : AmbientSpace)
    (s : Finset (Option PositiveSequences)) (N : ℕ) :
    (ambientApproximation z s N).1 = (yApproximation z N).1 := by
  simp [ambientApproximation]

theorem ambientApproximation_snd_apply (z : AmbientSpace)
    (s : Finset (Option PositiveSequences)) (N : ℕ) (α : PositiveSequences)
    (hα : some α ∈ s) :
    (ambientApproximation z s N).2 α = z.2 α := by
  classical
  simp [ambientApproximation, ambientCorrection, hα]

theorem exists_norm_yApproximation_fst_sub_lt (z : AmbientSpace)
    {ε : ℝ} (hε : 0 < ε) :
    ∃ N, ‖(yApproximation z N).1 - z.1‖ < ε := by
  have htend : Filter.Tendsto
      (fun n : ℕ => ‖z.1.1 (n : OnePoint ℕ)‖) Filter.atTop (nhds 0) :=
    by
      simpa [Real.norm_eq_abs] using
        ((continuous_abs.tendsto (0 : ℝ)).comp
          (Aliprantis.Question2.C0.tendsto_zero z.1))
  have heventually : ∀ᶠ n : ℕ in Filter.atTop,
      ‖z.1.1 (n : OnePoint ℕ)‖ < ε :=
    (tendsto_order.1 htend).2 ε hε
  obtain ⟨N, hN⟩ := Filter.eventually_atTop.1 heventually
  refine ⟨N, ?_⟩
  have hcont : ‖((yApproximation z N).1.1 - z.1.1 : C(OnePoint ℕ, ℝ))‖ < ε := by
    apply (((yApproximation z N).1.1 - z.1.1 : C(OnePoint ℕ, ℝ)).norm_lt_iff hε).2
    intro p
    induction p using OnePoint.rec with
    | infty =>
        have hzinf : z.1.1 (OnePoint.infty : OnePoint ℕ) = 0 := z.1.2
        simpa [yApproximation_fst_infty, hzinf] using hε
    | coe m =>
        by_cases hm : m < N
        · simp [yApproximation_fst_apply, hm, hε]
        · simpa [yApproximation_fst_apply, hm] using hN m (Nat.le_of_not_gt hm)
  exact hcont

/-- Pairs whose first coordinate is zero and whose second coordinate is a
finitely supported function on `P S`. -/
noncomputable def finiteSupportSubmodule : Submodule ℝ AmbientSpace where
  carrier := {x | x.1 = 0 ∧ (Function.support x.2).Finite}
  zero_mem' := ⟨rfl, by simp⟩
  add_mem' := by
    rintro x y ⟨hx0, hx⟩ ⟨hy0, hy⟩
    constructor
    · simp [hx0, hy0]
    · exact (hx.union hy).subset (Function.support_add x.2 y.2)
  smul_mem' := by
    rintro r x ⟨hx0, hx⟩
    constructor
    · simp [hx0]
    · exact hx.subset (Function.support_smul_subset_right (fun _ => r) x.2)

/-- The ideal `I` of finitely supported functions on `P S`, extended by zero
on the `c₀` coordinate. -/
noncomputable def I : OrderIdeal AmbientSpace :=
  OrderIdeal.ofSolid finiteSupportSubmodule (by
    intro x y hx hxy
    rcases hx with ⟨hx0, hxfin⟩
    constructor
    · have hfirst := hxy.1
      change |y.1| ≤ |x.1| at hfirst
      rw [hx0, abs_zero] at hfirst
      apply le_antisymm
      · exact (le_abs_self y.1).trans hfirst
      · rw [← neg_nonpos]
        exact (neg_le_abs y.1).trans hfirst
    · apply hxfin.subset
      intro α hyα
      change y.2 α ≠ 0 at hyα
      change x.2 α ≠ 0
      intro hxα
      have hcoord := hxy.2 α
      change |y.2 α| ≤ |x.2 α| at hcoord
      rw [hxα, abs_zero] at hcoord
      exact hyα (abs_eq_zero.mp (le_antisymm hcoord (abs_nonneg (y.2 α)))))

@[simp]
theorem mem_I_iff (x : AmbientSpace) :
    x ∈ I ↔ x.1 = 0 ∧ (Function.support x.2).Finite :=
  Iff.rfl


/-- The vector sublattice `X = Y + I` from Section 3.2. -/
noncomputable def XSubLattice : VectorSublattice AmbientSpace :=
  VectorSublattice.ofAbsClosed (Y.toSubmodule + I.toSubmodule) (by
    intro x hx
    obtain ⟨y, hy, i, hi, rfl⟩ := Submodule.mem_sup.mp hx
    let r : AmbientSpace := |y + i| - |y|
    have hr_le : |r| ≤ |i| := by
      rw [abs_le']
      constructor
      · change |y + i| - |y| ≤ |i|
        exact sub_le_iff_le_add'.mpr (abs_add_le y i)
      · dsimp [r]
        rw [neg_sub]
        apply sub_le_iff_le_add'.mpr
        have h := abs_add_le (y + i) (-i)
        simpa [add_assoc] using h
    have hrI : r ∈ I := I.mem_of_abs_le_abs hi hr_le
    apply Submodule.mem_sup.mpr
    refine ⟨|y|, Y.abs_mem hy, r, hrI, ?_⟩
    simp [r])

/-- The underlying type of the space `X` in the counterexample. -/
noncomputable abbrev X := XSubLattice.toSubmodule

/-- Membership in `X` is precisely membership in the algebraic sum `Y + I`. -/
theorem mem_XSubLattice_iff (x : AmbientSpace) :
    x ∈ XSubLattice ↔
      ∃ y ∈ Y, ∃ i ∈ I, y + i = x := by
  change x ∈ Y.toSubmodule ⊔ I.toSubmodule ↔ _
  exact Submodule.mem_sup

theorem zero_ambientCorrection_mem_I (z : AmbientSpace)
    (s : Finset (Option PositiveSequences)) (N : ℕ) :
    (0, ambientCorrection z s N) ∈ I := by
  rw [mem_I_iff]
  constructor
  · rfl
  · have hinj : Function.Injective (fun α : PositiveSequences => some α) :=
      fun _ _ h => Option.some.inj h
    have hfinite : ({α | some α ∈ (s : Set (Option PositiveSequences))} :
        Set PositiveSequences).Finite :=
      s.finite_toSet.preimage hinj.injOn
    apply hfinite.subset
    intro α hα
    change ambientCorrection z s N α ≠ 0 at hα
    change some α ∈ (s : Set (Option PositiveSequences))
    by_contra hnot
    have hnot' : some α ∉ s := by simpa using hnot
    exact hα (by simp [ambientCorrection, hnot'])

theorem ambientApproximation_mem_X (z : AmbientSpace)
    (s : Finset (Option PositiveSequences)) (N : ℕ) :
    ambientApproximation z s N ∈ XSubLattice := by
  rw [mem_XSubLattice_iff]
  exact ⟨yApproximation z N, yApproximation_mem_Y z N,
    (0, ambientCorrection z s N), zero_ambientCorrection_mem_I z s N, rfl⟩

/-! ### The product topology on the ambient space -/

/-- Projection to the `c₀` coordinate as a linear map. -/
noncomputable def ambientFst : AmbientSpace →ₗ[ℝ] C0 where
  toFun x := x.1
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- Evaluation of the `ℝᴾˢ` coordinate at `α`. -/
noncomputable def ambientEval (α : PositiveSequences) : AmbientSpace →ₗ[ℝ] ℝ where
  toFun x := x.2 α
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- The seminorm given by the uniform norm on the `c₀` coordinate. -/
noncomputable def ambientNormLatticeSeminorm : LatticeSeminorm AmbientSpace where
  toSeminorm := (normSeminorm ℝ C0).comp ambientFst
  monotone_abs' := by
    intro x y hxy
    change ‖x.1.1‖ ≤ ‖y.1.1‖
    exact HasSolidNorm.solid hxy.1

/-- The seminorm given by evaluating the second coordinate at `α`. -/
noncomputable def ambientEvaluationLatticeSeminorm (α : PositiveSequences) :
    LatticeSeminorm AmbientSpace where
  toSeminorm := (normSeminorm ℝ ℝ).comp (ambientEval α)
  monotone_abs' := by
    intro x y hxy
    simpa [Seminorm.comp_apply, ambientEval, Real.norm_eq_abs] using hxy.2 α

/-- The family consisting of the `c₀` norm and all coordinate seminorms on
`ℝᴾˢ`. -/
noncomputable def ambientLatticeSeminormFamily :
    Option PositiveSequences → LatticeSeminorm AmbientSpace
  | none => ambientNormLatticeSeminorm
  | some α => ambientEvaluationLatticeSeminorm α

@[simp]
theorem ambientLatticeSeminormFamily_none_apply (x : AmbientSpace) :
    (ambientLatticeSeminormFamily none).toSeminorm x = ‖x.1‖ := by
  rfl

@[simp]
theorem ambientLatticeSeminormFamily_some_apply (α : PositiveSequences)
    (x : AmbientSpace) :
    (ambientLatticeSeminormFamily (some α)).toSeminorm x = |x.2 α| := by
  simp [ambientLatticeSeminormFamily, ambientEvaluationLatticeSeminorm,
    Seminorm.comp_apply, ambientEval, Real.norm_eq_abs]

/-- The topology generated by the uniform norm on `c₀` and pointwise
convergence on `ℝᴾˢ`; equivalently, the product topology described in the
paper. -/
@[implicit_reducible]
noncomputable def ambientTopology : TopologicalSpace AmbientSpace :=
  (LatticeSeminorm.toSeminormFamily ambientLatticeSeminormFamily).moduleFilterBasis.topology'

/-- The ordinary product of the norm topology on `c₀` and the pointwise
product topology on `ℝᴾˢ`. -/
@[implicit_reducible]
noncomputable def ambientProductTopology : TopologicalSpace AmbientSpace :=
  inferInstance

theorem ambient_withLatticeSeminorms :
    @WithLatticeSeminorms AmbientSpace _ _ _ _ ambientTopology
      (Option PositiveSequences) ambientLatticeSeminormFamily := by
  unfold WithLatticeSeminorms
  exact @WithSeminorms.mk ℝ AmbientSpace (Option PositiveSequences) _ _ _
    (LatticeSeminorm.toSeminormFamily ambientLatticeSeminormFamily)
    ambientTopology rfl

/-- The ambient topology is locally convex-solid. -/
theorem ambient_isLocallyConvexSolidVectorLattice :
    @IsLocallyConvexSolidVectorLattice AmbientSpace _ _ _ _ ambientTopology := by
  exact (@isLocallyConvexSolidVectorLattice_iff_exists_withLatticeSeminorms
    AmbientSpace _ _ _ _ ambientTopology).2
      ⟨Option PositiveSequences, ambientLatticeSeminormFamily,
        ambient_withLatticeSeminorms⟩

/-- The seminorm topology used above is exactly the product topology stated
in the paper. -/
theorem ambientTopology_eq_productTopology :
    ambientTopology = ambientProductTopology := by
  have hproduct : @IsTopologicalAddGroup AmbientSpace ambientProductTopology _ := by
    unfold ambientProductTopology
    infer_instance
  have hsource : @nhds AmbientSpace ambientTopology 0 =
      ⨅ i, Filter.comap
        (⇑(LatticeSeminorm.toSeminormFamily ambientLatticeSeminormFamily i)) (nhds 0) := by
    letI : TopologicalSpace AmbientSpace := ambientTopology
    letI : IsTopologicalAddGroup AmbientSpace :=
      ambient_isLocallyConvexSolidVectorLattice.toIsTopologicalAddGroup
    exact (SeminormFamily.withSeminorms_iff_nhds_eq_iInf
      (p := LatticeSeminorm.toSeminormFamily ambientLatticeSeminormFamily)).mp
        ambient_withLatticeSeminorms
  apply IsTopologicalAddGroup.ext
    ambient_isLocallyConvexSolidVectorLattice.toIsTopologicalAddGroup hproduct
  rw [hsource]
  change (⨅ i, Filter.comap
    (⇑(LatticeSeminorm.toSeminormFamily ambientLatticeSeminormFamily i)) (nhds 0)) =
      @nhds AmbientSpace ambientProductTopology 0
  rw [show @nhds AmbientSpace ambientProductTopology 0 =
    (nhds (0 : C0) ×ˢ nhds (0 : PositiveSequences → ℝ)) from nhds_prod_eq]
  rw [← @comap_norm_nhds_zero C0 _]
  rw [nhds_pi]
  rw [Filter.pi]
  rw [iInf_option]
  congr 1
  · change Filter.comap (norm ∘ Prod.fst) (nhds 0) =
      Filter.comap Prod.fst (Filter.comap norm (nhds 0))
    rw [Filter.comap_comap]
    rfl
  · rw [Filter.comap_iInf]
    apply iInf_congr
    intro α
    rw [Filter.comap_comap]
    have hfun :
        (⇑(LatticeSeminorm.toSeminormFamily ambientLatticeSeminormFamily (some α))) =
          norm ∘ Function.eval α ∘ Prod.snd := by
      funext x
      simp [Real.norm_eq_abs]
    rw [hfun]
    change Filter.comap (norm ∘ Function.eval α ∘ Prod.snd) (nhds 0) =
      Filter.comap (Function.eval α ∘ Prod.snd) (nhds 0)
    conv_rhs => rw [← @comap_norm_nhds_zero ℝ _]
    rw [Filter.comap_comap]

private theorem ambientLatticeSeminormFamily_separating (x : AmbientSpace)
    (hx : x ≠ 0) :
    ∃ i, (ambientLatticeSeminormFamily i).toSeminorm x ≠ 0 := by
  by_cases hfirst : x.1 = 0
  · have hsecond : x.2 ≠ 0 := by
      intro h
      exact hx (Prod.ext hfirst h)
    have hexists : ∃ α, x.2 α ≠ 0 := by
      by_contra h
      push Not at h
      exact hsecond (funext h)
    obtain ⟨α, hα⟩ := hexists
    exact ⟨some α, by simpa [abs_ne_zero] using hα⟩
  · exact ⟨none, by simpa using (norm_ne_zero_iff.mpr hfirst)⟩

/-- The ambient topology is Hausdorff. -/
theorem ambient_t2Space : @T2Space AmbientSpace ambientTopology := by
  letI : TopologicalSpace AmbientSpace := ambientTopology
  letI : IsLocallyConvexSolidVectorLattice AmbientSpace :=
    ambient_isLocallyConvexSolidVectorLattice
  letI : T1Space AmbientSpace :=
    ambient_withLatticeSeminorms.T1_of_separating
      ambientLatticeSeminormFamily_separating
  infer_instance

/-! ### The subspace topology on `X` -/

/-- The topology on `X` is the subspace topology inherited from
`c₀ × ℝᴾˢ`. -/
@[implicit_reducible]
noncomputable def xTopology : TopologicalSpace X :=
  ambientTopology.induced (XSubLattice.toSubmodule.subtype : X → AmbientSpace)

/-- The inclusion `X ↪ c₀ × ℝᴾˢ` induces the topology on `X`. -/
theorem x_inclusion_isInducing :
    @Topology.IsInducing X AmbientSpace xTopology ambientTopology
      (XSubLattice.toSubmodule.subtype : X → AmbientSpace) :=
  @Topology.IsInducing.mk X AmbientSpace xTopology ambientTopology
    (XSubLattice.toSubmodule.subtype : X → AmbientSpace) rfl

/-- The ambient lattice seminorms restricted to `X`. -/
noncomputable def xLatticeSeminormFamily (i : Option PositiveSequences) :
    LatticeSeminorm X where
  toSeminorm := (ambientLatticeSeminormFamily i).toSeminorm.comp
    XSubLattice.toSubmodule.subtype
  monotone_abs' := by
    intro x y hxy
    exact (ambientLatticeSeminormFamily i).monotone_abs' hxy

theorem x_withLatticeSeminorms :
    @WithLatticeSeminorms X _ _ _ _ xTopology
      (Option PositiveSequences) xLatticeSeminormFamily := by
  letI : TopologicalSpace AmbientSpace := ambientTopology
  letI : TopologicalSpace X := xTopology
  unfold WithLatticeSeminorms
  exact XSubLattice.toSubmodule.subtype.withSeminorms_induced
    ambient_withLatticeSeminorms

/-- With its subspace topology, `X` is locally convex-solid. -/
theorem x_isLocallyConvexSolidVectorLattice :
    @IsLocallyConvexSolidVectorLattice X _ _ _ _ xTopology := by
  exact (@isLocallyConvexSolidVectorLattice_iff_exists_withLatticeSeminorms
    X _ _ _ _ xTopology).2
      ⟨Option PositiveSequences, xLatticeSeminormFamily,
        x_withLatticeSeminorms⟩

/-- With its subspace topology, `X` is Hausdorff. -/
theorem x_t2Space : @T2Space X xTopology := by
  letI : TopologicalSpace AmbientSpace := ambientTopology
  letI : T2Space AmbientSpace := ambient_t2Space
  letI : TopologicalSpace X := xTopology
  exact T2Space.of_injective_continuous Subtype.val_injective
    x_inclusion_isInducing.continuous

/-- Summary of the structural part of Section 3.2: `X`, with the topology
induced by its natural inclusion into `c₀ × ℝᴾˢ`, is a Hausdorff locally
convex-solid vector lattice. -/
theorem x_isHausdorff_locallyConvexSolid :
    @T2Space X xTopology ∧
      @IsLocallyConvexSolidVectorLattice X _ _ _ _ xTopology :=
  ⟨x_t2Space, x_isLocallyConvexSolidVectorLattice⟩

/-- The natural inclusion of `X` into the ambient product has dense range. -/
theorem x_inclusion_denseRange :
    @DenseRange AmbientSpace ambientTopology X
      (XSubLattice.toSubmodule.subtype : X → AmbientSpace) := by
  letI : TopologicalSpace AmbientSpace := ambientTopology
  intro z
  rw [mem_closure_iff_nhds]
  intro U hU
  rcases ambient_withLatticeSeminorms.hasBasis_ball.mem_iff.mp hU with
    ⟨⟨s, ε⟩, hε, hsU⟩
  obtain ⟨N, hN⟩ := exists_norm_yApproximation_fst_sub_lt z hε
  let a := ambientApproximation z s N
  have ha_ball : a ∈
      (s.sup (LatticeSeminorm.toSeminormFamily ambientLatticeSeminormFamily)).ball z ε := by
    rw [Seminorm.mem_ball]
    apply Seminorm.finset_sup_apply_lt hε
    intro i hi
    cases i with
    | none =>
        simpa [a, ambientLatticeSeminormFamily_none_apply,
          ambientApproximation_fst] using hN
    | some α =>
        have haα := ambientApproximation_snd_apply z s N α hi
        simp [ambientLatticeSeminormFamily_some_apply, a, haα, hε]
  refine ⟨a, hsU ha_ball, ?_⟩
  exact ⟨⟨a, ambientApproximation_mem_X z s N⟩, rfl⟩

/-! ### Lemma 3.3: identification of the completion -/

/-- The inclusion of `X` is also inducing when the ambient space is equipped
with its ordinary product topology. -/
theorem x_inclusion_isInducing_product :
    @Topology.IsInducing X AmbientSpace xTopology ambientProductTopology
      (XSubLattice.toSubmodule.subtype : X → AmbientSpace) := by
  rw [← ambientTopology_eq_productTopology]
  exact x_inclusion_isInducing

/-- The canonical additive-group uniformity associated to the topology on `X`. -/
@[implicit_reducible]
noncomputable def xUniformSpace : UniformSpace X := by
  letI : TopologicalSpace X := xTopology
  letI : IsLocallyConvexSolidVectorLattice X :=
    x_isLocallyConvexSolidVectorLattice
  exact IsTopologicalAddGroup.rightUniformSpace X

/-- The product `c₀ × ℝᴾˢ`, with the natural inclusion of `X`, as an
abstract completion of `X`. -/
noncomputable def xCompletionPackage :
    @AbstractCompletion X xUniformSpace := by
  letI : TopologicalSpace X := xTopology
  letI : IsLocallyConvexSolidVectorLattice X :=
    x_isLocallyConvexSolidVectorLattice
  letI : T2Space X := x_t2Space
  letI : UniformSpace X := xUniformSpace
  letI : IsUniformAddGroup X := isUniformAddGroup_of_addCommGroup
  letI : IsClosed (c0Sublattice : Set C(OnePoint ℕ, ℝ)) :=
    c0Sublattice_isClosed
  exact
    { space := AmbientSpace
      coe := XSubLattice.toSubmodule.subtype
      uniformStruct := inferInstance
      complete := inferInstance
      separation := inferInstance
      isUniformInducing := by
        let J := XSubLattice.toSubmodule.subtype.toAddMonoidHom
        change IsUniformInducing (J : X → AmbientSpace)
        exact AddMonoidHom.isUniformInducing_of_isInducing
          x_inclusion_isInducing_product
      dense := by
        have hd := x_inclusion_denseRange
        rw [ambientTopology_eq_productTopology] at hd
        exact hd }

/-- The uniform equivalence from the concrete product completion to mathlib's
canonical completion of `X`. -/
noncomputable def xCompletionEquiv :
    AmbientSpace ≃ᵤ @UniformSpace.Completion X xUniformSpace :=
  @AbstractCompletion.compareEquiv X xUniformSpace xCompletionPackage
    (@UniformSpace.Completion.cPkg X xUniformSpace)

@[simp]
theorem xCompletionEquiv_inclusion (x : X) :
    xCompletionEquiv (XSubLattice.toSubmodule.subtype x) =
      (x : @UniformSpace.Completion X xUniformSpace) := by
  exact @AbstractCompletion.compare_coe X xUniformSpace xCompletionPackage
    (@UniformSpace.Completion.cPkg X xUniformSpace) x

/-- Lemma 3.3: the topological completion of `X` is `c₀ × ℝᴾˢ`,
together with the natural inclusion. -/
theorem lemma3_3 :
    ∃ e : AmbientSpace ≃ᵤ @UniformSpace.Completion X xUniformSpace,
      ∀ x : X,
        e (XSubLattice.toSubmodule.subtype x) =
          (x : @UniformSpace.Completion X xUniformSpace) := by
  exact ⟨xCompletionEquiv, xCompletionEquiv_inclusion⟩

/-! ### Failure and validity of property `(B, i)` -/

/-- The sequence `sₙ` from Lemma 3.4: its first `n` entries are one and
all remaining entries are zero. -/
noncomputable def c0PartialOnes (n : ℕ) : C0 := by
  refine ⟨OnePoint.continuousMapMkNat (fun m => if m < n then 1 else 0) 0 ?_, ?_⟩
  · refine tendsto_const_nhds.congr' ?_
    filter_upwards [Filter.eventually_ge_atTop n] with m hm
    simp [Nat.not_lt.mpr hm]
  · change OnePoint.continuousMapMkNat (fun m => if m < n then 1 else 0) 0 _
        OnePoint.infty = 0
    simp [OnePoint.continuousMapMkNat, OnePoint.continuousMapMkDiscrete,
      OnePoint.continuousMapMk]

@[simp]
theorem c0PartialOnes_apply (n m : ℕ) :
    (c0PartialOnes n).1 (m : OnePoint ℕ) = if m < n then 1 else 0 := by
  simp [c0PartialOnes, OnePoint.continuousMapMkNat,
    OnePoint.continuousMapMkDiscrete, OnePoint.continuousMapMk]

@[simp]
theorem c0PartialOnes_infty (n : ℕ) :
    (c0PartialOnes n).1 (OnePoint.infty : OnePoint ℕ) = 0 := by
  simp [c0PartialOnes, OnePoint.continuousMapMkNat,
    OnePoint.continuousMapMkDiscrete, OnePoint.continuousMapMk]

/-- The increasing sequence used to witness the failure of `(B, i)` in the
completion. -/
noncomputable def ambientPartialOnes (n : ℕ) : AmbientSpace :=
  (c0PartialOnes n, 0)

theorem ambientPartialOnes_monotone : Monotone ambientPartialOnes := by
  intro n m hnm
  constructor
  · intro p
    change (c0PartialOnes n).1 p ≤ (c0PartialOnes m).1 p
    induction p using OnePoint.rec with
    | infty => simp
    | coe k =>
        simp only [c0PartialOnes_apply]
        split_ifs with hkn hkm
        · rfl
        · exact False.elim (hkm (hkn.trans_le hnm))
        · norm_num
        · rfl
  · exact le_rfl

theorem ambientPartialOnes_nonneg (n : ℕ) : 0 ≤ ambientPartialOnes n := by
  constructor
  · intro p
    change 0 ≤ (c0PartialOnes n).1 p
    induction p using OnePoint.rec with
    | infty => simp
    | coe k =>
        rw [c0PartialOnes_apply]
        split_ifs <;> norm_num
  · exact le_rfl

theorem c0PartialOnes_norm_le_one (n : ℕ) : ‖c0PartialOnes n‖ ≤ 1 := by
  change ‖(c0PartialOnes n).1‖ ≤ 1
  apply ((c0PartialOnes n).1.norm_le zero_le_one).2
  intro p
  induction p using OnePoint.rec with
  | infty => simp
  | coe k =>
      rw [c0PartialOnes_apply]
      split_ifs <;> norm_num

theorem ambientPartialOnes_isVonNBounded :
    letI : TopologicalSpace AmbientSpace := ambientTopology
    Bornology.IsVonNBounded ℝ (Set.range ambientPartialOnes) := by
  letI : TopologicalSpace AmbientSpace := ambientTopology
  letI : IsLocallyConvexSolidVectorLattice AmbientSpace :=
    ambient_isLocallyConvexSolidVectorLattice
  apply ambient_withLatticeSeminorms.isVonNBounded_iff_seminorm_bounded.2
  intro i
  refine ⟨2, by norm_num, ?_⟩
  rintro x ⟨n, rfl⟩
  cases i with
  | none =>
      simpa only [ambientLatticeSeminormFamily_none_apply, ambientPartialOnes] using
        (c0PartialOnes_norm_le_one n).trans_lt (by norm_num)
  | some α => simp [ambientPartialOnes]

theorem c0PartialOnes_not_cauchySeq : ¬ CauchySeq c0PartialOnes := by
  intro h
  obtain ⟨N, hN⟩ := (Metric.cauchySeq_iff'.1 h (1 / 2) (by norm_num))
  have hdist := hN (N + 1) (Nat.le_succ N)
  have hone : (1 : ℝ) ≤ dist (c0PartialOnes (N + 1)) (c0PartialOnes N) := by
    rw [dist_eq_norm]
    change 1 ≤ ‖(c0PartialOnes (N + 1)).1 - (c0PartialOnes N).1‖
    have hpoint := ContinuousMap.norm_coe_le_norm
      ((c0PartialOnes (N + 1)).1 - (c0PartialOnes N).1) (N : OnePoint ℕ)
    simpa [c0PartialOnes_apply] using hpoint
  linarith

/-- Lemma 3.4: the completion `c₀ × ℝᴾˢ` does not have property
`(B, i)`. -/
theorem lemma3_4 :
    ¬ @Bi AmbientSpace _ _ _ _ ambientTopology
      ambient_isLocallyConvexSolidVectorLattice.toIsLocallySolidVectorLattice := by
  letI : TopologicalSpace AmbientSpace := ambientTopology
  letI : IsLocallyConvexSolidVectorLattice AmbientSpace :=
    ambient_isLocallyConvexSolidVectorLattice
  intro hBi
  have hambient := hBi.cauchySeq_of_monotone_nonneg_isVonNBounded
    ambientPartialOnes_monotone ambientPartialOnes_nonneg
      ambientPartialOnes_isVonNBounded
  letI : UniformSpace AmbientSpace :=
    IsTopologicalAddGroup.rightUniformSpace AmbientSpace
  letI : IsUniformAddGroup AmbientSpace := isUniformAddGroup_of_addCommGroup
  let fstHom : AmbientSpace →+ C0 := ambientFst.toAddMonoidHom
  have hfstContinuous : Continuous (fstHom : AmbientSpace → C0) := by
    have h : @Continuous AmbientSpace C0 ambientProductTopology _ Prod.fst :=
      continuous_fst
    rw [← ambientTopology_eq_productTopology] at h
    simpa [fstHom, ambientFst] using h
  have hfstUniform : UniformContinuous (fstHom : AmbientSpace → C0) :=
    uniformContinuous_addMonoidHom_of_continuous hfstContinuous
  exact c0PartialOnes_not_cauchySeq
    (hfstUniform.comp_cauchySeq hambient)

namespace LatticeExpression

theorem eval_zero_tuple_real {n : ℕ} (e : LLexpr n) :
    LLexpr.eval (fun _ : Fin n => (0 : ℝ)) e = 0 := by
  induction e <;> simp_all

theorem eval_const_smul_of_nonneg_real {n : ℕ} (c : ℝ) (hc : 0 ≤ c)
    (v : Fin n → ℝ) (e : LLexpr n) :
    LLexpr.eval (fun i => c * v i) e = c * LLexpr.eval v e := by
  induction e with
  | zero => simp
  | var i => rfl
  | add e₁ e₂ h₁ h₂ => simp [h₁, h₂, mul_add]
  | smul r e h =>
      rw [LLexpr.eval_smul, h, LLexpr.eval_smul]
      simp only [smul_eq_mul]
      ring
  | sup e₁ e₂ h₁ h₂ =>
      rw [LLexpr.eval_sup, h₁, h₂, LLexpr.eval_sup]
      exact (mul_max_of_nonneg _ _ hc).symm
  | inf e₁ e₂ h₁ h₂ =>
      rw [LLexpr.eval_inf, h₁, h₂, LLexpr.eval_inf]
      exact (mul_min_of_nonneg _ _ hc).symm

theorem continuous_eval_real {n : ℕ} (e : LLexpr n) :
    Continuous (fun v : Fin n → ℝ => LLexpr.eval v e) := by
  induction e with
  | zero => exact continuous_const
  | var i => exact continuous_apply i
  | add e₁ e₂ h₁ h₂ => exact h₁.add h₂
  | smul r e h => exact h.const_smul r
  | sup e₁ e₂ h₁ h₂ => exact h₁.max h₂
  | inf e₁ e₂ h₁ h₂ => exact h₁.min h₂

/-- A lattice-linear expression that is positive in a direction can be made
arbitrarily large along every affine ray in that direction.  The integer
choice of the scale also lets us avoid one prescribed nonnegative value. -/
theorem exists_nnreal_eval_add_smul_gt {n : ℕ} (e : LLexpr n)
    (v w : Fin n → ℝ) (hv : 0 < LLexpr.eval v e) (B : ℝ) (a : NNReal) :
    ∃ t : NNReal, t ≠ a ∧ B < LLexpr.eval (fun i => w i + t * v i) e := by
  let q : ℕ → Fin n → ℝ := fun k i => v i + w i / ((k : ℝ) + 1)
  have hq : Filter.Tendsto q Filter.atTop (nhds v) := by
    rw [tendsto_pi_nhds]
    intro i
    simpa [q, div_eq_mul_inv, mul_comm] using
      (tendsto_const_nhds.add
        ((tendsto_one_div_add_atTop_nhds_zero_nat (𝕜 := ℝ)).mul_const (w i)) :
          Filter.Tendsto (fun k : ℕ => v i + (1 / ((k : ℝ) + 1)) * w i)
            Filter.atTop (nhds (v i + 0 * w i)))
  have heval : Filter.Tendsto (fun k => LLexpr.eval (q k) e) Filter.atTop
      (nhds (LLexpr.eval v e)) :=
    (continuous_eval_real e).continuousAt.tendsto.comp hq
  have hevent : ∀ᶠ k in Filter.atTop,
      LLexpr.eval v e / 2 < LLexpr.eval (q k) e :=
    heval.eventually (eventually_gt_nhds (half_lt_self hv))
  have hlarge : ∀ᶠ k : ℕ in Filter.atTop,
      B < ((k : ℝ) + 1) * (LLexpr.eval v e / 2) := by
    have ht : Filter.Tendsto (fun k : ℕ => (k : ℝ) + 1) Filter.atTop Filter.atTop :=
      by
        simpa [Function.comp_def] using
          (tendsto_natCast_atTop_atTop (R := ℝ)).comp (Filter.tendsto_add_atTop_nat 1)
    exact (ht.atTop_mul_const (half_pos hv)).eventually (Filter.eventually_gt_atTop B)
  have havoid : ∀ᶠ k : ℕ in Filter.atTop, (a : ℝ) < (k : ℝ) + 1 := by
    have ht : Filter.Tendsto (fun k : ℕ => (k : ℝ) + 1) Filter.atTop Filter.atTop :=
      by
        simpa [Function.comp_def] using
          (tendsto_natCast_atTop_atTop (R := ℝ)).comp (Filter.tendsto_add_atTop_nat 1)
    exact ht.eventually (Filter.eventually_gt_atTop (a : ℝ))
  obtain ⟨k, hk, hklarge, hkavoid⟩ := (hevent.and (hlarge.and havoid)).exists
  let t : NNReal := ⟨k + 1, by positivity⟩
  refine ⟨t, ?_, ?_⟩
  · intro hta
    have hcoe : (a : ℝ) = (k : ℝ) + 1 := by
      calc
        (a : ℝ) = (t : ℝ) := congrArg (fun z : NNReal => (z : ℝ)) hta.symm
        _ = (k : ℝ) + 1 := rfl
    exact (ne_of_lt hkavoid) hcoe
  · have hscale : 0 ≤ (k : ℝ) + 1 := by positivity
    have hqscale :
        (fun i => w i + ((k : ℝ) + 1) * v i) =
          fun i => ((k : ℝ) + 1) * q k i := by
      funext i
      simp only [q]
      field_simp
      ring
    change B < LLexpr.eval (fun i => w i + ((k : ℝ) + 1) * v i) e
    rw [hqscale, eval_const_smul_of_nonneg_real _ hscale]
    exact hklarge.trans_le (mul_le_mul_of_nonneg_left hk.le hscale)

end LatticeExpression

/-- Evaluation of the first coordinate at a natural number, as a vector
lattice homomorphism. -/
noncomputable def ambientFirstEvalVecLatHom (m : ℕ) : VecLatHom AmbientSpace ℝ where
  toFun x := x.1.1 (m : OnePoint ℕ)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  map_sup' _ _ := rfl
  map_inf' _ _ := rfl

/-- Evaluation of a coordinate in the second factor, as a vector lattice
homomorphism. -/
noncomputable def ambientSecondEvalVecLatHom (α : PositiveSequences) :
    VecLatHom AmbientSpace ℝ where
  toFun x := x.2 α
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  map_sup' _ _ := rfl
  map_inf' _ _ := rfl

/-- Finite lattice-linear data representing an element generated by the
family `(aⱼ)`. -/
structure GeneratorRepresentation (y : AmbientSpace) where
  arity : ℕ
  indices : Fin arity → ℕ
  expr : LLexpr arity
  eval_eq : LLexpr.eval (fun i => generator (indices i)) expr = y

noncomputable def GeneratorRepresentation.support {y : AmbientSpace}
    (r : GeneratorRepresentation y) : Finset ℕ :=
  Finset.univ.image r.indices

theorem exists_generatorRepresentation {y : AmbientSpace} (hy : y ∈ Y) :
    Nonempty (GeneratorRepresentation y) := by
  change y ∈ (VectorSublattice.generated (Set.range generator) : Set AmbientSpace) at hy
  rw [LLexpr.generated_eq_iUnion_combinations] at hy
  simp only [Set.mem_iUnion] at hy
  obtain ⟨n, x, hx⟩ := hy
  obtain ⟨e, he⟩ := hx
  let a : Fin n → ℕ := fun i => Classical.choose (x i).2
  have ha (i : Fin n) : generator (a i) = (x i).1 :=
    Classical.choose_spec (x i).2
  refine ⟨⟨n, a, e, ?_⟩⟩
  rw [← he]
  congr 2
  funext i
  exact ha i

theorem GeneratorRepresentation.first_apply {y : AmbientSpace}
    (r : GeneratorRepresentation y) (m : ℕ) :
    y.1.1 (m : OnePoint ℕ) =
      LLexpr.eval (fun i => if m = r.indices i then (1 : ℝ) else 0) r.expr := by
  calc
    y.1.1 (m : OnePoint ℕ) = ambientFirstEvalVecLatHom m y := rfl
    _ = ambientFirstEvalVecLatHom m
        (LLexpr.eval (fun i => generator (r.indices i)) r.expr) := by rw [r.eval_eq]
    _ = LLexpr.eval
        (fun i => ambientFirstEvalVecLatHom m (generator (r.indices i))) r.expr :=
      LLexpr.map_eval _ _ _
    _ = _ := by
      apply congrArg (fun z : Fin r.arity → ℝ => LLexpr.eval z r.expr)
      funext i
      change (if m = r.indices i then (1 : ℝ) else 0) =
        (generator (r.indices i)).1.1 (m : OnePoint ℕ)
      rw [generator_fst_apply]

theorem GeneratorRepresentation.second_apply {y : AmbientSpace}
    (r : GeneratorRepresentation y) (α : PositiveSequences) :
    y.2 α = LLexpr.eval (fun i => (α (r.indices i) : ℝ)) r.expr := by
  calc
    y.2 α = ambientSecondEvalVecLatHom α y := rfl
    _ = ambientSecondEvalVecLatHom α
        (LLexpr.eval (fun i => generator (r.indices i)) r.expr) := by rw [r.eval_eq]
    _ = LLexpr.eval
        (fun i => ambientSecondEvalVecLatHom α (generator (r.indices i))) r.expr :=
      LLexpr.map_eval _ _ _
    _ = _ := by rfl

theorem GeneratorRepresentation.first_apply_eq_zero_of_not_mem_support
    {y : AmbientSpace} (r : GeneratorRepresentation y) {m : ℕ}
    (hm : m ∉ r.support) : y.1.1 (m : OnePoint ℕ) = 0 := by
  rw [r.first_apply]
  have hz : (fun i => if m = r.indices i then (1 : ℝ) else 0) = fun _ => 0 := by
    funext i
    simp only [GeneratorRepresentation.support, Finset.mem_image, Finset.mem_univ,
      true_and] at hm
    have hne : m ≠ r.indices i := by
      intro h
      exact hm ⟨i, h.symm⟩
    simp [hne]
  rw [hz]
  exact LatticeExpression.eval_zero_tuple_real r.expr

/-- The single-coordinate growth step in the diagonal construction from the
proof of Lemma 3.5. -/
theorem GeneratorRepresentation.exists_update_second_gt {y : AmbientSpace}
    (r : GeneratorRepresentation y) (base : PositiveSequences) (m : ℕ)
    (hm : 0 < y.1.1 (m : OnePoint ℕ)) (B : ℝ) (forbidden : NNReal) :
    ∃ value : NNReal, value ≠ forbidden ∧
      B < y.2 (Function.update base m value) := by
  let v : Fin r.arity → ℝ :=
    fun i => if m = r.indices i then 1 else 0
  let w : Fin r.arity → ℝ := fun i => base (r.indices i)
  have hv : 0 < LLexpr.eval v r.expr := by
    rw [r.first_apply] at hm
    simpa [v] using hm
  let forbiddenIncrement : NNReal := forbidden - base m
  obtain ⟨t, htne, ht⟩ := LatticeExpression.exists_nnreal_eval_add_smul_gt
    r.expr v w hv B forbiddenIncrement
  have hvalue : base m + t ≠ forbidden := by
    intro heq
    by_cases hlt : forbidden < base m
    · have : forbidden < base m + t :=
        hlt.trans_le (le_add_of_nonneg_right t.2)
      exact (ne_of_gt this) heq
    · apply htne
      apply NNReal.eq
      have heqReal := congrArg (fun z : NNReal => (z : ℝ)) heq
      simp only [NNReal.coe_add] at heqReal
      simp [forbiddenIncrement, NNReal.coe_sub (le_of_not_gt hlt)]
      linarith
  refine ⟨base m + t, hvalue, ?_⟩
  rw [r.second_apply]
  apply lt_of_lt_of_eq ht
  apply congrArg (fun z : Fin r.arity → ℝ => LLexpr.eval z r.expr)
  funext i
  by_cases hi : r.indices i = m
  · dsimp [v, w]
    rw [if_pos hi.symm, mul_one]
    rw [Function.update_apply, if_pos hi, hi]
    rfl
  · dsimp [v, w]
    rw [if_neg (Ne.symm hi), mul_zero]
    rw [Function.update_apply, if_neg hi]
    exact add_zero _

/-- If a positive increasing norm-bounded sequence in `c₀` is not Cauchy,
then some fixed positive amount escapes every prescribed finite set of
coordinates, arbitrarily far along the sequence. -/
theorem c0_exists_escape_finite {f : ℕ → C0} (hmono : Monotone f)
    (hnonneg : ∀ n, 0 ≤ f n) (hbounded : ∃ R : ℝ, ∀ n, ‖f n‖ < R)
    (hnot : ¬ CauchySeq f) :
    ∃ ε > 0, ∀ (F : Finset ℕ) (N : ℕ),
      ∃ n ≥ N, ∃ m ∉ F, ε ≤ (f n).1 (m : OnePoint ℕ) := by
  obtain ⟨R, hR⟩ := hbounded
  have hcoordMono (m : ℕ) : Monotone (fun n => (f n).1 (m : OnePoint ℕ)) := by
    intro n k hnk
    exact hmono hnk (m : OnePoint ℕ)
  have hcoordBdd (m : ℕ) :
      BddAbove (Set.range fun n => (f n).1 (m : OnePoint ℕ)) := by
    refine ⟨R, ?_⟩
    rintro _ ⟨n, rfl⟩
    exact (le_abs_self _).trans
      ((f n).1.norm_coe_le_norm (m : OnePoint ℕ) |>.trans_lt (hR n)).le
  have hcoordCauchy (m : ℕ) :
      CauchySeq (fun n => (f n).1 (m : OnePoint ℕ)) :=
    (tendsto_atTop_ciSup (hcoordMono m) (hcoordBdd m)).cauchySeq
  rw [Metric.cauchySeq_iff'] at hnot
  push Not at hnot
  obtain ⟨ε, hε, hbad⟩ := hnot
  refine ⟨ε, hε, ?_⟩
  intro F N
  have hcoordTail (m : ℕ) :
      ∃ K, ∀ p ≥ K, ∀ q ≥ K,
        dist ((f p).1 (m : OnePoint ℕ)) ((f q).1 (m : OnePoint ℕ)) < ε :=
    Metric.cauchySeq_iff.1 (hcoordCauchy m) ε hε
  choose K hK using hcoordTail
  let N' := max N (F.sup K)
  obtain ⟨n, hnN', hn⟩ := hbad N'
  have hnorm : ε ≤ ‖(f n).1 - (f N').1‖ := by
    simpa [dist_eq_norm] using hn
  have hpoint : ∃ p : OnePoint ℕ,
      ε ≤ ‖((f n).1 - (f N').1) p‖ := by
    by_contra hall
    push Not at hall
    have := ((f n).1 - (f N').1).norm_lt_iff hε |>.2 hall
    exact (not_lt_of_ge hnorm) this
  obtain ⟨p, hp⟩ := hpoint
  induction p using OnePoint.rec with
  | infty =>
      have hninf : (f n).1 (OnePoint.infty : OnePoint ℕ) = 0 := (f n).2
      have hNinf : (f N').1 (OnePoint.infty : OnePoint ℕ) = 0 := (f N').2
      simp [hninf, hNinf] at hp
      exact (not_le_of_gt hε hp).elim
  | coe m =>
      have hN'n : N' ≤ n := hnN'
      have hmonoPoint : (f N').1 (m : OnePoint ℕ) ≤
          (f n).1 (m : OnePoint ℕ) := hmono hN'n _
      have hnonnegPoint : 0 ≤ (f N').1 (m : OnePoint ℕ) := hnonneg N' _
      change ε ≤ ‖(f n).1 (m : OnePoint ℕ) - (f N').1 (m : OnePoint ℕ)‖ at hp
      have hp' : ε ≤ (f n).1 (m : OnePoint ℕ) - (f N').1 (m : OnePoint ℕ) := by
        simpa [Real.norm_eq_abs, abs_of_nonneg (sub_nonneg.mpr hmonoPoint)] using hp
      have hmvalue : ε ≤ (f n).1 (m : OnePoint ℕ) := by
        linarith
      refine ⟨n, (le_max_left _ _).trans hnN', m, ?_, hmvalue⟩
      intro hmF
      have hKm : K m ≤ F.sup K := Finset.le_sup hmF
      have hKN' : K m ≤ N' := hKm.trans (le_max_right _ _)
      have hsmall := hK m n (hKN'.trans hnN') N' hKN'
      rw [Real.dist_eq] at hsmall
      rw [abs_of_nonneg (sub_nonneg.mpr hmonoPoint)] at hsmall
      exact (not_lt_of_ge hp') hsmall

/-! The following small recursive package implements the diagonal choice in
the second half of the paper's proof of Lemma 3.5. -/

structure DiagonalAccumulator where
  base : PositiveSequences
  used : Finset ℕ

structure DiagonalChoice where
  index : ℕ
  coordinate : ℕ
  value : NNReal

def IsDiagonalChoice (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (j : ℕ) (A : DiagonalAccumulator) (c : DiagonalChoice) : Prop :=
  c.coordinate ∉ A.used ∧
    c.coordinate ∈ (r c.index).support ∧
    0 < (y c.index).1.1 (c.coordinate : OnePoint ℕ) ∧
    c.value ≠ β j c.coordinate ∧
    (j : ℝ) < (y c.index).2
      (Function.update A.base c.coordinate c.value)

theorem exists_diagonalChoice (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ))
    (j : ℕ) (A : DiagonalAccumulator) :
    ∃ c, IsDiagonalChoice y r β j A c := by
  obtain ⟨n, m, hmA, hmpos⟩ := hescape A.used
  have hmSupport : m ∈ (r n).support := by
    by_contra hm
    have hz := (r n).first_apply_eq_zero_of_not_mem_support hm
    linarith
  obtain ⟨value, hvalueNe, hvalue⟩ :=
    (r n).exists_update_second_gt A.base m hmpos j (β j m)
  exact ⟨⟨n, m, value⟩, hmA, hmSupport, hmpos, hvalueNe, hvalue⟩

noncomputable def diagonalChoice (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ))
    (j : ℕ) (A : DiagonalAccumulator) : DiagonalChoice :=
  Classical.choose (exists_diagonalChoice y r β hescape j A)

theorem diagonalChoice_spec (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ))
    (j : ℕ) (A : DiagonalAccumulator) :
    IsDiagonalChoice y r β j A (diagonalChoice y r β hescape j A) :=
  Classical.choose_spec (exists_diagonalChoice y r β hescape j A)

noncomputable def diagonalAccumulator (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ)) : ℕ → DiagonalAccumulator
  | 0 => ⟨0, ∅⟩
  | j + 1 =>
      let A := diagonalAccumulator y r β hescape j
      let c := diagonalChoice y r β hescape j A
      ⟨Function.update A.base c.coordinate c.value,
        A.used ∪ (r c.index).support⟩

noncomputable def diagonalChoiceAt (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ)) (j : ℕ) : DiagonalChoice :=
  diagonalChoice y r β hescape j (diagonalAccumulator y r β hescape j)

theorem diagonalChoiceAt_spec (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ)) (j : ℕ) :
    IsDiagonalChoice y r β j (diagonalAccumulator y r β hescape j)
      (diagonalChoiceAt y r β hescape j) :=
  diagonalChoice_spec y r β hescape j _

@[simp]
theorem diagonalAccumulator_zero (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ)) :
    diagonalAccumulator y r β hescape 0 = ⟨0, ∅⟩ := rfl

@[simp]
theorem diagonalAccumulator_succ (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ)) (j : ℕ) :
    diagonalAccumulator y r β hescape (j + 1) =
      ⟨Function.update (diagonalAccumulator y r β hescape j).base
          (diagonalChoiceAt y r β hescape j).coordinate
          (diagonalChoiceAt y r β hescape j).value,
        (diagonalAccumulator y r β hescape j).used ∪
          (r (diagonalChoiceAt y r β hescape j).index).support⟩ := rfl

theorem diagonal_support_subset_used (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ))
    {i j : ℕ} (hij : i < j) :
    (r (diagonalChoiceAt y r β hescape i).index).support ⊆
      (diagonalAccumulator y r β hescape j).used := by
  induction j with
  | zero => omega
  | succ j ih =>
      rw [show j + 1 = Nat.succ j by omega, diagonalAccumulator_succ]
      intro m hm
      simp only [Finset.mem_union]
      by_cases h : i = j
      · subst i
        exact Or.inr hm
      · exact Or.inl (ih (by omega) hm)

theorem diagonal_coordinate_mem_used (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ))
    {i j : ℕ} (hij : i < j) :
    (diagonalChoiceAt y r β hescape i).coordinate ∈
      (diagonalAccumulator y r β hescape j).used :=
  diagonal_support_subset_used y r β hescape hij
    (diagonalChoiceAt_spec y r β hescape i).2.1

theorem diagonal_coordinate_injective (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ)) :
    Function.Injective
      (fun j => (diagonalChoiceAt y r β hescape j).coordinate) := by
  intro i j hij
  change (diagonalChoiceAt y r β hescape i).coordinate =
    (diagonalChoiceAt y r β hescape j).coordinate at hij
  rcases lt_trichotomy i j with hlt | heq | hgt
  · have hmem := diagonal_coordinate_mem_used y r β hescape hlt
    have hnot := (diagonalChoiceAt_spec y r β hescape j).1
    exact False.elim (hnot (by rw [← hij]; exact hmem))
  · exact heq
  · have hmem := diagonal_coordinate_mem_used y r β hescape hgt
    have hnot := (diagonalChoiceAt_spec y r β hescape i).1
    exact False.elim (hnot (by rw [hij]; exact hmem))

theorem diagonal_base_at_coordinate (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ))
    {i j : ℕ} (hij : i < j) :
    (diagonalAccumulator y r β hescape j).base
        (diagonalChoiceAt y r β hescape i).coordinate =
      (diagonalChoiceAt y r β hescape i).value := by
  induction j with
  | zero => omega
  | succ j ih =>
      rw [show j + 1 = Nat.succ j by omega, diagonalAccumulator_succ]
      change Function.update (diagonalAccumulator y r β hescape j).base
          (diagonalChoiceAt y r β hescape j).coordinate
          (diagonalChoiceAt y r β hescape j).value
          (diagonalChoiceAt y r β hescape i).coordinate =
        (diagonalChoiceAt y r β hescape i).value
      by_cases h : i = j
      · subst i
        simp
      · have hne : (diagonalChoiceAt y r β hescape i).coordinate ≠
            (diagonalChoiceAt y r β hescape j).coordinate := by
          intro heq
          exact h ((diagonal_coordinate_injective y r β hescape) heq)
        rw [Function.update_apply, if_neg hne]
        exact ih (by omega)

theorem diagonal_base_eq_zero_of_fresh (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ))
    (j k : ℕ)
    (hk : ∀ i < j, (diagonalChoiceAt y r β hescape i).coordinate ≠ k) :
    (diagonalAccumulator y r β hescape j).base k = 0 := by
  induction j with
  | zero => rfl
  | succ j ih =>
      rw [show j + 1 = Nat.succ j by omega, diagonalAccumulator_succ]
      change Function.update (diagonalAccumulator y r β hescape j).base
          (diagonalChoiceAt y r β hescape j).coordinate
          (diagonalChoiceAt y r β hescape j).value k = 0
      rw [Function.update_apply, if_neg (hk j (by omega) |>.symm)]
      exact ih (fun i hi => hk i (by omega))

noncomputable def diagonalAlpha (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ)) : PositiveSequences := by
  classical
  exact fun k =>
    if h : ∃ j, (diagonalChoiceAt y r β hescape j).coordinate = k then
      (diagonalChoiceAt y r β hescape (Classical.choose h)).value
    else 0

theorem diagonalAlpha_at_coordinate (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ)) (j : ℕ) :
    diagonalAlpha y r β hescape
        (diagonalChoiceAt y r β hescape j).coordinate =
      (diagonalChoiceAt y r β hescape j).value := by
  rw [diagonalAlpha, dif_pos ⟨j, rfl⟩]
  let h : ∃ i, (diagonalChoiceAt y r β hescape i).coordinate =
      (diagonalChoiceAt y r β hescape j).coordinate := ⟨j, rfl⟩
  have hindex : Classical.choose h = j :=
    diagonal_coordinate_injective y r β hescape (Classical.choose_spec h)
  simp only [hindex]

theorem GeneratorRepresentation.second_apply_eq_of_eq_on_support
    {y : AmbientSpace} (r : GeneratorRepresentation y)
    {α γ : PositiveSequences}
    (h : ∀ m ∈ r.support, α m = γ m) : y.2 α = y.2 γ := by
  rw [r.second_apply, r.second_apply]
  apply congrArg (fun z : Fin r.arity → ℝ => LLexpr.eval z r.expr)
  funext i
  exact congrArg (fun z : NNReal => (z : ℝ))
    (h (r.indices i) (Finset.mem_image.mpr ⟨i, Finset.mem_univ _, rfl⟩))

theorem diagonalAlpha_eq_base_succ_on_support (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ)) (j : ℕ) {k : ℕ}
    (hk : k ∈ (r (diagonalChoiceAt y r β hescape j).index).support) :
    diagonalAlpha y r β hescape k =
      (diagonalAccumulator y r β hescape (j + 1)).base k := by
  classical
  by_cases hex : ∃ i, (diagonalChoiceAt y r β hescape i).coordinate = k
  · let i := Classical.choose hex
    have hi : (diagonalChoiceAt y r β hescape i).coordinate = k :=
      Classical.choose_spec hex
    have hij : i ≤ j := by
      by_contra hnot
      have hji : j < i := Nat.lt_of_not_ge hnot
      have hkUsed : k ∈ (diagonalAccumulator y r β hescape i).used :=
        diagonal_support_subset_used y r β hescape hji hk
      have hiNot := (diagonalChoiceAt_spec y r β hescape i).1
      exact hiNot (by rw [hi]; exact hkUsed)
    calc
      diagonalAlpha y r β hescape k =
          diagonalAlpha y r β hescape
            (diagonalChoiceAt y r β hescape i).coordinate := by rw [hi]
      _ = (diagonalChoiceAt y r β hescape i).value :=
        diagonalAlpha_at_coordinate y r β hescape i
      _ = (diagonalAccumulator y r β hescape (j + 1)).base
          (diagonalChoiceAt y r β hescape i).coordinate :=
        (diagonal_base_at_coordinate y r β hescape (Nat.lt_succ_iff.mpr hij)).symm
      _ = (diagonalAccumulator y r β hescape (j + 1)).base k := by rw [hi]
  · have hAlpha : diagonalAlpha y r β hescape k = 0 := by
      simp [diagonalAlpha, hex]
    rw [hAlpha]
    exact (diagonal_base_eq_zero_of_fresh y r β hescape (j + 1) k
      (fun i hi hcoord => hex ⟨i, hcoord⟩)).symm

theorem diagonal_second_gt (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ)) (j : ℕ) :
    (j : ℝ) < (y (diagonalChoiceAt y r β hescape j).index).2
      (diagonalAlpha y r β hescape) := by
  let c := diagonalChoiceAt y r β hescape j
  let A := diagonalAccumulator y r β hescape j
  have hspec := diagonalChoiceAt_spec y r β hescape j
  have hdepends := (r c.index).second_apply_eq_of_eq_on_support
    (fun k hk => diagonalAlpha_eq_base_succ_on_support y r β hescape j hk)
  have hsucc : (diagonalAccumulator y r β hescape (j + 1)).base =
      Function.update A.base c.coordinate c.value := by
    rw [diagonalAccumulator_succ]
  rw [hsucc] at hdepends
  exact hdepends.symm ▸ hspec.2.2.2.2

theorem diagonalAlpha_ne_beta (y : ℕ → AmbientSpace)
    (r : ∀ n, GeneratorRepresentation (y n)) (β : ℕ → PositiveSequences)
    (hescape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
      0 < (y n).1.1 (m : OnePoint ℕ)) (j : ℕ) :
    diagonalAlpha y r β hescape ≠ β j := by
  intro heq
  let c := diagonalChoiceAt y r β hescape j
  have hvalue := (diagonalChoiceAt_spec y r β hescape j).2.2.2.1
  apply hvalue
  rw [← diagonalAlpha_at_coordinate y r β hescape j]
  exact congrFun heq c.coordinate

/-- Lemma 3.5: the space `X` has property `(B, i)`. -/
theorem lemma3_5 :
    @Bi X _ _ _ _ xTopology
      x_isLocallyConvexSolidVectorLattice.toIsLocallySolidVectorLattice := by
  letI : TopologicalSpace X := xTopology
  letI : IsLocallyConvexSolidVectorLattice X :=
    x_isLocallyConvexSolidVectorLattice
  constructor
  intro u huMono huNonneg huBounded
  letI : UniformSpace X := xUniformSpace
  letI : IsUniformAddGroup X := isUniformAddGroup_of_addCommGroup
  have hseminorm :=
    x_withLatticeSeminorms.isVonNBounded_iff_seminorm_bounded.mp huBounded
  have hfirstBound : ∃ R : ℝ, ∀ n, ‖(u n : AmbientSpace).1‖ < R := by
    obtain ⟨R, hR, hbound⟩ := hseminorm none
    refine ⟨R, fun n => ?_⟩
    have := hbound (u n) ⟨n, rfl⟩
    simpa [xLatticeSeminormFamily] using this
  have hsecondBound (a : PositiveSequences) :
      ∃ R : ℝ, ∀ n, |(u n : AmbientSpace).2 a| < R := by
    obtain ⟨R, hR, hbound⟩ := hseminorm (some a)
    refine ⟨R, fun n => ?_⟩
    have := hbound (u n) ⟨n, rfl⟩
    simpa [xLatticeSeminormFamily] using this
  have hdecomp (n : ℕ) :
      ∃ y ∈ Y, ∃ i ∈ I, y + i = (u n : AmbientSpace) :=
    mem_XSubLattice_iff (u n : AmbientSpace) |>.mp (u n).2
  choose y hy i hi hyi using hdecomp
  have hiFirst (n : ℕ) : (i n).1 = 0 := (mem_I_iff (i n)).mp (hi n) |>.1
  have hyFirst (n : ℕ) : (y n).1 = (u n : AmbientSpace).1 := by
    have h := congrArg Prod.fst (hyi n)
    simpa [hiFirst n] using h
  let r : ∀ n, GeneratorRepresentation (y n) :=
    fun n => Classical.choice (exists_generatorRepresentation (hy n))
  let exceptional : Set PositiveSequences :=
    ⋃ n, Function.support (i n).2
  have hexceptionalCountable : exceptional.Countable := by
    apply Set.countable_iUnion
    intro n
    exact ((mem_I_iff (i n)).mp (hi n)).2.countable
  obtain ⟨β, hβ⟩ :=
    Set.countable_iff_exists_subset_range.mp hexceptionalCountable
  have hySecond_of_not_mem {a : PositiveSequences} (ha : a ∉ exceptional) (n : ℕ) :
      (y n).2 a = (u n : AmbientSpace).2 a := by
    have hiZero : (i n).2 a = 0 := by
      by_contra hne
      exact ha (Set.mem_iUnion.mpr ⟨n, hne⟩)
    have h := congrArg (fun z : AmbientSpace => z.2 a) (hyi n)
    simpa [hiZero] using h
  let f : ℕ → C0 := fun n => (u n : AmbientSpace).1
  have hfMono : Monotone f := by
    intro n m hnm
    exact (huMono hnm).1
  have hfNonneg : ∀ n, 0 ≤ f n := fun n => (huNonneg n).1
  have hfBound : ∃ R : ℝ, ∀ n, ‖f n‖ < R := hfirstBound
  have hfCauchy : CauchySeq f := by
    by_contra hfNot
    obtain ⟨ε, hε, hescape⟩ :=
      c0_exists_escape_finite hfMono hfNonneg hfBound hfNot
    have hyEscape : ∀ F : Finset ℕ, ∃ n m, m ∉ F ∧
        0 < (y n).1.1 (m : OnePoint ℕ) := by
      intro F
      obtain ⟨n, hn, m, hmF, hm⟩ := hescape F 0
      refine ⟨n, m, hmF, ?_⟩
      rw [hyFirst]
      exact hε.trans_le hm
    let a := diagonalAlpha y r β hyEscape
    have haNotExceptional : a ∉ exceptional := by
      intro ha
      obtain ⟨j, hj⟩ := hβ ha
      exact diagonalAlpha_ne_beta y r β hyEscape j hj.symm
    obtain ⟨R, hR⟩ := hsecondBound a
    obtain ⟨j, hj⟩ := exists_nat_gt R
    let c := diagonalChoiceAt y r β hyEscape j
    have hyLarge : (j : ℝ) < (y c.index).2 a :=
      diagonal_second_gt y r β hyEscape j
    have huLarge : (j : ℝ) < (u c.index : AmbientSpace).2 a := by
      rwa [hySecond_of_not_mem haNotExceptional c.index] at hyLarge
    have huCoordNonneg : 0 ≤ (u c.index : AmbientSpace).2 a :=
      (huNonneg c.index).2 a
    have hboundedCoord := hR c.index
    rw [abs_of_nonneg huCoordNonneg] at hboundedCoord
    linarith
  have hsecondCauchy : CauchySeq (fun n => (u n : AmbientSpace).2) := by
    let limit : PositiveSequences → ℝ :=
      fun a => ⨆ n, (u n : AmbientSpace).2 a
    have htend : Filter.Tendsto (fun n => (u n : AmbientSpace).2)
        Filter.atTop (nhds limit) := by
      rw [tendsto_pi_nhds]
      intro a
      apply tendsto_atTop_ciSup
      · intro n m hnm
        exact (huMono hnm).2 a
      · obtain ⟨R, hR⟩ := hsecondBound a
        refine ⟨R, ?_⟩
        rintro _ ⟨n, rfl⟩
        exact (le_abs_self _).trans (hR n).le
    exact htend.cauchySeq
  have hambient : CauchySeq (fun n => (u n : AmbientSpace)) := by
    simpa [f] using hfCauchy.prodMk hsecondCauchy
  let J := XSubLattice.toSubmodule.subtype.toAddMonoidHom
  have hJ : IsUniformInducing (J : X → AmbientSpace) :=
    AddMonoidHom.isUniformInducing_of_isInducing x_inclusion_isInducing_product
  change Cauchy (Filter.map u Filter.atTop)
  apply hJ.cauchy_map_iff.mp
  simpa only [CauchySeq, Filter.map_map, Function.comp_def] using hambient

/-! ### Transporting the counterexample to the canonical completion -/

section CompletionTransfer

noncomputable local instance : TopologicalSpace X := xTopology
noncomputable local instance : IsLocallyConvexSolidVectorLattice X :=
  x_isLocallyConvexSolidVectorLattice
noncomputable local instance : T2Space X := x_t2Space
noncomputable local instance : UniformSpace X := xUniformSpace
noncomputable local instance : IsUniformAddGroup X := isUniformAddGroup_of_addCommGroup

private theorem x_inclusion_denseRange_product :
    @DenseRange AmbientSpace ambientProductTopology X
      (XSubLattice.toSubmodule.subtype : X → AmbientSpace) := by
  have h := x_inclusion_denseRange
  rw [ambientTopology_eq_productTopology] at h
  exact h

/-- The comparison equivalence preserves lattice suprema. -/
theorem xCompletionEquiv_map_sup (a b : AmbientSpace) :
    xCompletionEquiv (a ⊔ b) = xCompletionEquiv a ⊔ xCompletionEquiv b := by
  have hambientSup : Continuous
      (fun p : AmbientSpace × AmbientSpace => p.1 ⊔ p.2) := by
    have hτ : @Continuous (AmbientSpace × AmbientSpace) AmbientSpace
        (@instTopologicalSpaceProd AmbientSpace AmbientSpace ambientTopology ambientTopology)
        ambientTopology (fun p => p.1 ⊔ p.2) := by
      letI : TopologicalSpace AmbientSpace := ambientTopology
      letI : IsLocallyConvexSolidVectorLattice AmbientSpace :=
        ambient_isLocallyConvexSolidVectorLattice
      letI : UniformSpace AmbientSpace :=
        IsTopologicalAddGroup.rightUniformSpace AmbientSpace
      letI : IsUniformAddGroup AmbientSpace := isUniformAddGroup_of_addCommGroup
      exact ((isLocallySolidVectorLattice_iff_uniformContinuous_sup
        (E := AmbientSpace)).mp inferInstance).continuous
    rw [ambientTopology_eq_productTopology] at hτ
    exact hτ
  have hcompletionSup : Continuous
      (fun p : UniformSpace.Completion X × UniformSpace.Completion X => p.1 ⊔ p.2) :=
    ((isLocallySolidVectorLattice_iff_uniformContinuous_sup
      (E := UniformSpace.Completion X)).mp inferInstance).continuous
  refine x_inclusion_denseRange_product.induction_on₂ ?_ ?_ a b
  · exact isClosed_eq
      (xCompletionEquiv.continuous.comp hambientSup)
      (hcompletionSup.comp
        ((xCompletionEquiv.continuous.comp continuous_fst).prodMk
          (xCompletionEquiv.continuous.comp continuous_snd)))
  · intro x y
    calc
      xCompletionEquiv ((x : AmbientSpace) ⊔ (y : AmbientSpace)) =
          xCompletionEquiv ((x ⊔ y : X) : AmbientSpace) := by rfl
      _ = ((x ⊔ y : X) : UniformSpace.Completion X) :=
        xCompletionEquiv_inclusion (x ⊔ y)
      _ = (x : UniformSpace.Completion X) ⊔
          (y : UniformSpace.Completion X) :=
        map_sup (IsLocallySolidVectorLattice.toCompletionVecLatHom (E := X)) x y
      _ = xCompletionEquiv (x : AmbientSpace) ⊔
          xCompletionEquiv (y : AmbientSpace) := by
        exact congrArg₂ (fun p q : UniformSpace.Completion X => p ⊔ q)
          (xCompletionEquiv_inclusion x).symm
          (xCompletionEquiv_inclusion y).symm

/-- The comparison equivalence preserves addition. -/
theorem xCompletionEquiv_map_add (a b : AmbientSpace) :
    xCompletionEquiv (a + b) = xCompletionEquiv a + xCompletionEquiv b := by
  refine x_inclusion_denseRange_product.induction_on₂ ?_ ?_ a b
  · exact isClosed_eq
      (xCompletionEquiv.continuous.comp continuous_add)
      (continuous_add.comp
        ((xCompletionEquiv.continuous.comp continuous_fst).prodMk
          (xCompletionEquiv.continuous.comp continuous_snd)))
  · intro x y
    calc
      xCompletionEquiv ((x : AmbientSpace) + (y : AmbientSpace)) =
          xCompletionEquiv ((x + y : X) : AmbientSpace) := by rfl
      _ = ((x + y : X) : UniformSpace.Completion X) :=
        xCompletionEquiv_inclusion (x + y)
      _ = (x : UniformSpace.Completion X) + (y : UniformSpace.Completion X) :=
        map_add (IsLocallySolidVectorLattice.toCompletionVecLatHom (E := X)) x y
      _ = xCompletionEquiv (x : AmbientSpace) +
          xCompletionEquiv (y : AmbientSpace) := by
        exact congrArg₂ (fun p q : UniformSpace.Completion X => p + q)
          (xCompletionEquiv_inclusion x).symm
          (xCompletionEquiv_inclusion y).symm

/-- The comparison equivalence preserves real scalar multiplication. -/
theorem xCompletionEquiv_map_smul (c : ℝ) (a : AmbientSpace) :
    xCompletionEquiv (c • a) = c • xCompletionEquiv a := by
  refine x_inclusion_denseRange_product.induction_on a ?_ ?_
  · exact isClosed_eq
      (xCompletionEquiv.continuous.comp (continuous_id.const_smul c))
      ((xCompletionEquiv.continuous.const_smul c))
  · intro x
    calc
      xCompletionEquiv (c • (x : AmbientSpace)) =
          xCompletionEquiv ((c • x : X) : AmbientSpace) := by rfl
      _ = ((c • x : X) : UniformSpace.Completion X) :=
        xCompletionEquiv_inclusion (c • x)
      _ = c • (x : UniformSpace.Completion X) :=
        map_smul (IsLocallySolidVectorLattice.toCompletionVecLatHom (E := X)) c x
      _ = c • xCompletionEquiv (x : AmbientSpace) := by
        exact congrArg (fun z : UniformSpace.Completion X => c • z)
          (xCompletionEquiv_inclusion x).symm

@[simp]
theorem xCompletionEquiv_zero : xCompletionEquiv (0 : AmbientSpace) = 0 := by
  calc
    xCompletionEquiv (0 : AmbientSpace) =
        xCompletionEquiv ((0 : X) : AmbientSpace) := rfl
    _ = ((0 : X) : UniformSpace.Completion X) := xCompletionEquiv_inclusion 0
    _ = 0 := map_zero (IsLocallySolidVectorLattice.toCompletionVecLatHom (E := X))

/-- The comparison with the canonical completion as a continuous linear
equivalence. -/
noncomputable def xCompletionContinuousLinearEquiv :
    AmbientSpace ≃L[ℝ] UniformSpace.Completion X where
  toFun := xCompletionEquiv
  invFun := xCompletionEquiv.symm
  left_inv := xCompletionEquiv.symm_apply_apply
  right_inv := xCompletionEquiv.apply_symm_apply
  map_add' := xCompletionEquiv_map_add
  map_smul' := xCompletionEquiv_map_smul
  continuous_toFun := xCompletionEquiv.continuous
  continuous_invFun := xCompletionEquiv.symm.continuous

theorem xCompletionEquiv_le_iff (a b : AmbientSpace) :
    xCompletionEquiv a ≤ xCompletionEquiv b ↔ a ≤ b := by
  constructor
  · intro h
    rw [← sup_eq_right]
    apply xCompletionEquiv.injective
    rw [xCompletionEquiv_map_sup, sup_eq_right.mpr h]
  · intro h
    rw [← sup_eq_right, ← xCompletionEquiv_map_sup, sup_eq_right.mpr h]

/-- The canonical completion of `X` inherits the failure of property `(B, i)`
from its concrete realization. -/
theorem completion_not_Bi : ¬ Bi (UniformSpace.Completion X) := by
  intro hBi
  let v : ℕ → UniformSpace.Completion X :=
    fun n => xCompletionEquiv (ambientPartialOnes n)
  have hvMono : Monotone v := by
    intro n m hnm
    exact (xCompletionEquiv_le_iff _ _).2 (ambientPartialOnes_monotone hnm)
  have hvNonneg (n : ℕ) : 0 ≤ v n := by
    rw [← xCompletionEquiv_zero]
    exact (xCompletionEquiv_le_iff _ _).2 (ambientPartialOnes_nonneg n)
  have hvBounded : Bornology.IsVonNBounded ℝ (Set.range v) := by
    have h := ambientPartialOnes_isVonNBounded
    rw [ambientTopology_eq_productTopology] at h
    have himage := h.image xCompletionContinuousLinearEquiv.toContinuousLinearMap
    rw [← Set.range_comp] at himage
    simpa [v, Function.comp_def] using himage
  have hvNotCauchy : ¬ CauchySeq v := by
    intro hv
    apply c0PartialOnes_not_cauchySeq
    have hambient : CauchySeq ambientPartialOnes := by
      simpa [v, Function.comp_def] using
        xCompletionEquiv.symm.uniformContinuous.comp_cauchySeq hv
    let fstHom : AmbientSpace →+ C0 := ambientFst.toAddMonoidHom
    have hfstUniform : UniformContinuous (fstHom : AmbientSpace → C0) :=
      uniformContinuous_addMonoidHom_of_continuous continuous_fst
    exact hfstUniform.comp_cauchySeq hambient
  apply hvNotCauchy
  have hv := hBi.cauchySeq_of_monotone_nonneg_isVonNBounded
    hvMono hvNonneg hvBounded
  have heq :
      IsTopologicalAddGroup.rightUniformSpace (UniformSpace.Completion X) =
        (inferInstance : UniformSpace (UniformSpace.Completion X)) :=
    IsUniformAddGroup.rightUniformSpace_eq
  rw [heq] at hv
  exact hv

end CompletionTransfer

/-- Theorem 3.6: there exists a Hausdorff locally convex-solid vector lattice
with property `(B, i)` whose topological completion does not have property
`(B, i)`. -/
theorem theorem3_6 :
  ∃ (E : Type) (_ : AddCommGroup E) (_ : Lattice E)
    (_ : IsOrderedAddMonoid E) (_ : VectorLattice E)
    (_ : TopologicalSpace E) (_ : T2Space E)
    (_ : IsLocallyConvexSolidVectorLattice E),
    Bi E ∧
      letI : UniformSpace E := IsTopologicalAddGroup.rightUniformSpace E
      letI : IsUniformAddGroup E := isUniformAddGroup_of_addCommGroup
      ¬ Bi (UniformSpace.Completion E) := by
  refine ⟨X, inferInstance, inferInstance, inferInstance, inferInstance,
    xTopology, x_t2Space, x_isLocallyConvexSolidVectorLattice, ?_⟩
  exact ⟨lemma3_5, completion_not_Bi⟩

end Aliprantis.Question2
