name = "aliprantis"
version = "0.1.0"
defaultTargets = ["Aliprantis"]

[[require]]
name = "banLat"
git = "https://github.com/davidmunozlahoz/banlat.git"
rev = "v0.1.0"

[[lean_lib]]
name = "Aliprantis"

[[lean_exe]]
name = "aliprantis"
root = "Main"
